### ISSUE TITLE
lambda test error:  Can't find ./options

### ISSUE THREAD

**Issue by jdavidow** [rgraciano/echo-sonos#1]
{
  "errorMessage": "Cannot find module './options'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._resolveFilename (module.js:338:15)",
    "Function.Module._load (module.js:280:25)",
    "Module.require (module.js:364:17)",
    "require (module.js:380:17)",
    "Object.<anonymous> (/var/task/index.js:5:15)",
    "Module._compile (module.js:456:26)",
    "Object.Module._extensions..js (module.js:474:10)",
    "Module.load (module.js:356:32)",
    "Function.Module._load (module.js:312:12)",
    "Module.require (module.js:364:17)"
  ]
}

**Comment by jdavidow** [comment]
Ah.  Your instructions say to rename the options.example.js file to "config", you must have changed that to "options".  Done.  This error doesn't occur anymore; you might want to change your readme.

**Comment by rgraciano** [comment]
Will do, thanks

**Comment by iainfowler** [comment]
Hi,

I am getting a similar error to the above I have copied options.example.js to options.js but get the below error when running the test on Lambda.

I am running node.js v6.9.4 in Windows 7 and can send commands to it externally that play and pause sonos all ok.

{
  "errorMessage": "Cannot find module './options'",
  "errorType": "Error",
  "stackTrace": [
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)",
    "Object.<anonymous> (/var/task/index.js:8:15)",
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)"
  ]
}
