### ISSUE TITLE
Looking for help to add in Amazon Audio Controls to Sonos Echo Skill or request it  as a feature.

### ISSUE THREAD

**Issue by Zmav** [rgraciano/echo-sonos#103]
Have tried to get this working on my own but I'm Really new to JS and still learning. Would love this to work as Alexa is a bit picky about how you talk to her. She always picks up the Play/Pause/Skip etc part but sometimes not the Sonos part so i'm constantly having to repeat myself and really annunciate the Sonos part and its getting very annoying. its not the skills fault.
Was hoping to either request someone who has this working if i can see there code and do it myself or if someone would be willing to write it and add it on here. Many thanks in advance.

**Comment by thosirl** [comment]
See here - https://github.com/rgraciano/echo-sonos/issues/57

**Comment by Zmav** [comment]
Thanks i saw that but couldn't get it working, so i had another go and got it working eventually. But now after a day its stopped working. Now i have absolutely no idea why though it no longer seems to play the blank audio file but it also gives no error?

**Comment by Zmav** [comment]
Nevermind sorted it, apparently if you mess with the lambda function it helps to turn the skill off and on again in the developer console!
