### ISSUE TITLE
Playing Artists without LineIn

### ISSUE THREAD

**Issue by adamkylegreen** [rgraciano/echo-sonos#105]
I'm trying to play music using the command:
"Alexa, ask sonos to play ARTIST NAME in the ROOM"

But I get the response:
This command does not work unless you set default Linein.

Is it possible to use the command without a line-in?

**Comment by pheintzelman** [comment]
@adamkylegreen That should work it is picking up the wrong intent.  Did you try a few times?

**Comment by adamkylegreen** [comment]
I couldn't get it working even with the fix. I removed the LineInIntents and now it's working. 
I'll have a proper look at the code tonight and see if I can work out a fix

**Comment by pheintzelman** [comment]
@adamkylegreen Let me know what you figure out. I don't have any music setup in my Sonos system (directly) so this is hard for me to test. But the utterances are not that similar... if it can't handle:

"Sonos play in living room" and "Sonos play ARTIST in living room"  as separate intents the music intent could handle both.

As a side note it likely isn't the line-in intent but the play in room intent that is causing issues.

**Comment by zeppomedio** [comment]
@adamkylegreen can you give the latest a try? We now use the Amazon built-in music intents and made some small tweaks to utterances and intents. As part of working on the change, I noticed the PlayInRoom has stopped interfering, at least on my system.

**Comment by threesquared** [comment]
I am having the same issue. I am using "UK English" which does not support the built in music intents AFAIK

**Comment by petebanham** [comment]
I am having the same issue and deleting the  PlayInRoomIntent intents also fixes it for me.

**Comment by pheintzelman** [comment]
A better long term solution might be to merge the PlayInRoomIntent with the play music intent. But I also assume the UK will get the more advanced slot types at some point.

**Comment by petebanham** [comment]
Hi,  sorry I am having a slow brain day....  When you say merge the intents what do you mean please? Just add all playinroom commands to the playmusic one? I am comfortable changing intents but not with changing the code. :-)  thanks

**Comment by pheintzelman** [comment]
@petebanham I meant combining them in the code.
