### ISSUE TITLE
Is it possible to change the radio system?

### ISSUE THREAD

**Issue by Zmav** [rgraciano/echo-sonos#107]
Was wondering if it would be possible to change the radio station tuner as in the UK we dont have SXS, its Tune in. Happy to try and do the work.
Just need to know where to start and if its even possible.
If anyone can help Thanks.
PS Awesome work done on this Thanks for all the time and effort,!

**Comment by pheintzelman** [comment]
node-sonos-http-api has an issue open to add tune-in

https://github.com/jishi/node-sonos-http-api/issues/366

**Comment by petebanham** [comment]
I have partially  worked around this by adding the radio stations I normally listen too as favorites and  then "Ask Sonos to play the favourite FAVOURITE_NAME in ROOM"  works.
