### ISSUE TITLE
Lamba crash

### ISSUE THREAD

**Issue by tlc** [rgraciano/echo-sonos#11]
"Alexa, use Sonos to play test" works.  But when I try a "Next track" utterance I get a lambda crash.
<img width="1055" alt="screen shot 2015-12-22 at 10 36 30 am" src="https://cloud.githubusercontent.com/assets/19436/11958853/4b5f9632-a898-11e5-81ba-6daf86865f28.png">

**Comment by tlc** [comment]
Found it.
actOnCoordinator needs a JSON.parse() call for the /zones response.

Thanks!

**Comment by tlc** [comment]
Not worth a fork/pull.

```
    var handleZonesResponse = function (responseJson) {
        responseJson = JSON.parse(responseJson);
        ...
```

**Comment by rgraciano** [comment]
Thanks; I removed a JSON.parse elsewhere and forgot to update this function
