### ISSUE TITLE
test work, but voice not with preset

### ISSUE THREAD

**Issue by ddqp** [rgraciano/echo-sonos#110]
Hi ,

I tried the test script in Lambda, it can trigger sonos to play preset, but when I speak with echo "Alexa, ask sonos to play pop", it gives me answer "OK", then nothing else, no sonos playing.

By the way, the voice command "play favorite pop, or pause, resume" work fine.

below is the preset file content:

{
    "pop": {
      "players": [
        { "roomName": "living_room", "volume": 20}
      ],
      "state": "PLAYING",
      "favorite": "pop",
      "playMode": "SHUFFLE",
      "pauseOthers": true
    },
   "rap": {
      "players": [
        { "roomName": "living_room", "volume": 20}
      ],
      "state": "PLAYING",
      "favorite": "pop",
      "uri": "x-rincon-stream:RINCON_0000000000001500",
      "playMode": "SHUFFLE",
      "pauseOthers": true
    },
    "pop rap": {
      "players": [
        {"roomName": "living_room", "volume": 20}
      ],
      "state": "PLAYING",
      "favorite": "Rap (Pop)",
      "uri": "x-rincon-stream:RINCON_0000000000001500",
      "playMode": "SHUFFLE",
      "pauseOthers": true
    },
    "rock": {
      "players": [
        {"roomName": "living_room", "volume": 20}
      ],
      "state": "PLAYING",
      "favorite": "Rock",
      "uri": "x-rincon-stream:RINCON_0000000000001500",
      "playMode": "SHUFFLE",
      "pauseOthers": true
    }
}

**Comment by funnybutrandom** [comment]
You're using the wrong command to trigger playlists, this is a list of the utterances you can use:

play preset {Preset}
playlist {Preset}
playlist {Preset}
play playlist {Preset}
play playlist {Preset}
start playlist {Preset}
start playlist {Preset}
Plus all the room variances, but I don't have them saved in my amazon skill to copy.

**Comment by ddqp** [comment]
ahhh,  thanks, got it,

however, the readme says below, so I thought it should be "Alexa, ask sonos to play Rock".

Usage
Global commands (no rooms required):
Presets: "Alexa, ask sonos to play Rock"

**Comment by rgraciano** [comment]
@ddqp - i believe the invocation changes depending on whether or not "advanced" mode is selected
