### ISSUE TITLE
Playing a Spotify playlist by name

### ISSUE THREAD

**Issue by chearmstrong** [rgraciano/echo-sonos#111]
I have followed the steps to get everything up and running. It seems to work OK and can play artist radio from Spotify with no issues.

What I can't seem to work out is how to play a specific playlist by name - do I need to save the names of all of my playlist in the presets?

Sorry if I'm mis-understanding. Just need some clarification.

**Comment by chearmstrong** [comment]
OK, so I think I worked out I need to save them to my favourites (unless there's a better way?).

Would still appreciate some clarification though, just to clear things up - also, I can't seem to get the line-in to work too. 

This is what I have in options:


```
var options = {
  appid: getDefault('APPID', ' amzn1.ask.skill.6a11fe8b-bb3d-4a5e-a35b-a01bd14ab20e'),
  host: getDefault('HOST', 'chearmstrong.mooo.com'),
  port: getDefault('PORT', '5005'),
  headers: {
      'Authorization': 'Basic ' + auth,
      'Content-Type': 'application/json'
  },

  useHttps: getDefault('USE_HTTPS', false), // Change to true if you setup node-sonos-http-api with HTTPS
  rejectUnauthorized: getDefault('REJECT_UNAUTHORIZED', false), // Change to false if you self-signed your certificate
  defaultRoom: getDefault('DEFAULT_ROOM', 'kitchen'),				        // Allows you to specify a default room when one is not specified in the utterance
  defaultMusicService: getDefault('DEFAULT_MUSIC_SERVICE', 'spotify'), // Supports presets, apple, spotify, deezer, or library
  advancedMode: getDefault('ADVANCED_MODE', true),             // Allows you to specify and change default rooms and music services. Requires additional AWS setup
  useSQS: getDefault('USE_SQS', false),   // Use AWS SQS and node-sqs-proxy for secure communications
  defaultLinein: getDefault('DEFAULT_LINEIN', 'living room')              // Allows you to specify a default Linein (e.g. with a dot connected) 
};
```

**Comment by pheintzelman** [comment]
I haven't used spotify playlist with this skill. But I don't think https://github.com/jishi/node-sonos-http-api has a method to directly play a spotify playlist. You could open an issue in that project.

**Comment by chearmstrong** [comment]
No problem - thanks @pheintzelman
