### ISSUE TITLE
help - newbie

### ISSUE THREAD

**Issue by DirtySurti** [rgraciano/echo-sonos#113]
Hi - I have created the skill and also got so far down the road with AWS Lambada setup.
When I test it I get error: {
  "errorMessage": "Handler 'handler' missing on module 'index'"
}

also I cant see where I am supposed to upload the src.zip file to

**Comment by pheintzelman** [comment]
![image](https://cloud.githubusercontent.com/assets/2145906/22352207/0747399a-e3d0-11e6-8671-0d6898a3de39.png)

Make sure you change the dropdown.

**Comment by DirtySurti** [comment]
brill - making progress - now I get invalid application id testing in lambada however I have double checked and its correct ???

**Comment by pheintzelman** [comment]
Is your skill and lambda in the same region? Alexa skills are only available for certain regions make sure your lambda function is also in that region.

**Comment by DirtySurti** [comment]
I can set location as Ireland in Lambada
where do I set it on the Amazon Skill ?

**Comment by thosirl** [comment]
Under Configuration, you will see Endpoint, this should be AWS Lambda, and then pick Europe as the Geographical region, and then put in here the ARN of your Lambda function.

**Comment by pheintzelman** [comment]
For all amazon services the region is in the upper right of the screen. It is in the same place for the skill and the lambda function. These need to be the same. If they are not change the lambda function to the region of the skill.

**Comment by DirtySurti** [comment]
doh my bad - i assumed the test script would pick up the appid from config.

**Comment by DirtySurti** [comment]
node-sonos-http-api is accessible externally ok
lambada tests ok too
however Alexa Dot cant seem to find the skill still

**Comment by DirtySurti** [comment]
i cant hit my node-sonons externally and play music etc
just dont seem to work with Alexa still

**Comment by DirtySurti** [comment]
I am also tryin to setup the TTS - I assume I need to edit the settings file however I have installed the node-sonos-http via a docker image. I have managed to SSH to my Synology and goto volume1/docker location but see no files or folders in there.

**Comment by pheintzelman** [comment]
Are all the aws service on the same account as the dot? Also make sure you put the skill into test or it will not be available.

**Comment by DirtySurti** [comment]
Hi. Firstly thank you all for your help, time and patience. It's much appreciated.

Yes all using the same login account details.
What do you mean put the skill into test sorry ??

**Comment by DirtySurti** [comment]
so via  the alexa skill i can get my sonos to resume and pause ok via the simulator

**Comment by DirtySurti** [comment]
ok looks like i need to I need to submit for certification ? button is disabled as publishing information ios not green ticked - all others are - are the icons mandatory I assume ?

**Comment by DirtySurti** [comment]
just to update - i now have it working with the Echo
issues was I am from the UK so had to change the language of skill to English uk and that solved it (also had to amend the intent schema accordingly for UK)
