### ISSUE TITLE
Trouble right from the start

### ISSUE THREAD

**Issue by merrick777** [rgraciano/echo-sonos#114]
As others have said- Sorry for newbie-type questions!
- per instructions I installed nstall node-sonos-http-api via Terminal (on my mac). When I looked for it via 'Finder' I found that it installed into {myusername}/node_modules/sonos-http-api.   Inside the /sonos-http-api folder I have a few files, and folders 'cache', 'lib', and 'static'.   I downloaded node-sonos-http-api/presets.json and (as per Step 3 instructions) need to put it into node-sonos-http-api root directory.... which doesn't exist (I have /sonos-http-api without "node"). 
- Step 4: Again, I don't have "/node-sonos-http-api" but I do have "/sonos-http-api".
Can you pls tell me where I'm going wrong??
Thnaks!

**Comment by pheintzelman** [comment]
Sounds like you ended up with the wrong node package. Just download it from this link https://github.com/jishi/node-sonos-http-api/archive/master.zip

**Comment by merrick777** [comment]
Thank you... Yes, that was better. So I edited the presets. NPM Start gave me errors so I tried json validator. It found error, but what do I do to fix this error?


![screen shot 2017-01-28 at 1 20 35 am](https://cloud.githubusercontent.com/assets/22691436/22394881/77b36340-e4fa-11e6-8e21-fc6b3f571724.jpg)
![screen shot 2017-01-28 at 1 35 43 am](https://cloud.githubusercontent.com/assets/22691436/22394882/89276414-e4fa-11e6-8e05-b4299fe7eedb.jpg)

**Comment by pheintzelman** [comment]
You need to do 
npm install 
before npm start

**Comment by merrick777** [comment]
Wow... Yes, looks like it worked. My bad, I somehow overlooked 'npm install' in the instructions. I'm getting there....
1) Would it be ok to be having this on MyCloud NAS drive? I see that I shouldn't be doing this on my mac because I also have the Sonos client running.
2) Testing: I tried http://yourserverip:5005/zones with the IP external IP address that I got from whatismyip.com  and also tried my internal (192.168....) and both returned 'Site Cannot Be Reached'. What should I be using?

(Thanks again and again!)

**Comment by pheintzelman** [comment]
1. I am not familiar with running node on MyCloud. If you are able to get the sever running it should be fine. I haven't had any issues using the server and client on one machine.

2. Are you able to hit localhost? Common issues here, firewall, network type (should be private), port forwarding not setup, no static ip for computer running node

**Comment by merrick777** [comment]
Configuring Lambda service, I'm confused by the instructions.... 

> Step 5: Go into this repo's lambda/src directory and copy options.example.js to options.js. It's recommended you DO NOT edit the options.js file (leave all defaults), because it's easier to customize this later.

> 
I see options.example.js but where is options.js?

Then it says 

> Step 6: In lambda/src, zip up everything. On Mac/Linux, cd src; chmod a+r *.js; zip src.zip *.js. Make sure you don't capture the folder, just the files.

> 
How do I zip the 3 files? I use a Mac, so if I'm supposed to do this in Terminal, how would I cd (change directory) to the location of the files?

Thanks for any help!

**Comment by evansgo** [comment]
This is the same issue I had, something must have changed in the instructions...
I've now downloaded from the link you sent (above) unzipped and moved it to the user folder. I then ran npm install, not much happened, I changed the presets, then ran npm start. All seems to be working, but spotify is still broken so that must be something else.
