### ISSUE TITLE
Lambda Error getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by steve772** [rgraciano/echo-sonos#119]
Getting the following:

"The Lambda service encountered an error: getaddrinfo ENOTFOUND" and then "mydyndnsaddress mydyndnsaddress:5005". 

Testing mydyndnsaddress:5005 from my web browser works fine.  I am able to control my Sonos.

Any thoughts?

**Comment by pheintzelman** [comment]
Does your host setting include the protocol(http/https)? it should just be your domain name.

**Comment by steve772** [comment]
@pheintzelmam I removed the http:// and it works great now. Thanks!
