### ISSUE TITLE
Lambda NOT recognizing/loading src.zip files

### ISSUE THREAD

**Issue by mhonard** [rgraciano/echo-sonos#12]
When I browse to the repos "lambda/src" directory containing the src.zip file the lambda function zip upload does NOT see the *.zip file which is 4k. I've made sure I am in the correct directory and tried multiple "zip" programs.  Any idea what's up?

**Comment by mhonard** [comment]
Never mind, too tired I guess.  Happy Holidays

**Comment by andyhud** [comment]
Did you get this to work in the end? I get the same problem. Upload files but it says "too many files zip file" even though its just those 3 files needed?

Anyone?
