### ISSUE TITLE
Having a mare 

### ISSUE THREAD

**Issue by jdrussell78** [rgraciano/echo-sonos#120]
So I am trying to configure lambda etc to get this app working.  But really struggling.

I feel like I do get further each time, but now I am getting a time out when trying to run the test

{
  "errorMessage": "2017-01-30T17:39:17.884Z f47ba45c-e712-11e6-a460-4b221773c86f Task timed out after 30.00 seconds"
}

Here's the log output

START RequestId: 1b1546ca-e714-11e6-9568-5f591917da49 Version: $LATEST
2017-01-30T17:47:05.020Z	1b1546ca-e714-11e6-9568-5f591917da49	session applicationId: amzn1.ask.skill.0576360d-8a85-48b1-bb7e-01b4c277158c
2017-01-30T17:47:05.077Z	1b1546ca-e714-11e6-9568-5f591917da49	dispatch intent = PlayPresetIntent
2017-01-30T17:47:05.077Z	1b1546ca-e714-11e6-9568-5f591917da49	PlayPresetIntent received
2017-01-30T17:47:05.078Z	1b1546ca-e714-11e6-9568-5f591917da49	Sending HTTP request to: /preset/test
END RequestId: 1b1546ca-e714-11e6-9568-5f591917da49
REPORT RequestId: 1b1546ca-e714-11e6-9568-5f591917da49	Duration: 30001.52 ms	Billed Duration: 30000 ms 	Memory Size: 128 MB	Max Memory Used: 16 MB	
2017-01-30T17:47:32.152Z 1b1546ca-e714-11e6-9568-5f591917da49 Task timed out after 30.00 seconds

Also, what does this actually mean (from the readme)

**copy options.example.js to options.js**

Copy it to where?  I don't follow.

"Go into this repo's lambda/src directory and copy options.example.js to options.js. It's recommended you DO NOT edit the options.js file (leave all defaults), because it's easier to customize this later.

Thanks in advance, been trying to get this to work all day long.

**Comment by pheintzelman** [comment]
copy options.example.js and rename the copy to options.js not having an options.js in your src.zip is sure to cause loads of issue.

**Comment by jdrussell78** [comment]
Thanks. Ok yes. That's what I thought it meant. In the src.zip file is the original options.example.js and options.js

Is that ok ?

Thanks for your reply.

**Comment by pheintzelman** [comment]
options.example.js will not be used so I would delete it from the src but isn't a big deal.

**Comment by jdrussell78** [comment]
Ok cool. Will do. I don't think this is going to be the problem then. 

Any ideas what could be causing the time out ? 

The lambda function does have its own code other than the src.zip file. Does that code need to be cleared out ?

Just trying to think of other reasons why it wouldn't be working. 

NPM is running on the server. That's fine. I can go to my IP on port 5050 and control sonos that way, so that all works. 

I've setup the Alexa skill and reference that APPID as one of the variables in the lambda configuration. 

I was having issues with the interaction model. But that is working now (based in EU so had to use NAMES). 

I feel like I am really close.

**Comment by pheintzelman** [comment]
Your using an external ip right? I think some UK users had timeout issues did you look through the other issues.

**Comment by jdrussell78** [comment]
when you say am i using an external IP, where should i be using that as the HOST?

I setup a dyns.cx DNS name, and then that is configured to an IP address.  

If I connect to that DNS name it takes me to my router where the server is based.

**Comment by jdrussell78** [comment]
Sorted !!

It was the inbound firewall rule !!!

Thanks for your help.
