### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by jdrussell78** [rgraciano/echo-sonos#122]
Hi,

When I ask "Alexa, ask sonos"

I get "There was a problem with the requested skills response"

In the Lambda logs, I see:

"errorMessage": "onLaunch should be overriden by subclass"

Can someone help me to understand what the problem is?

Also if I ask

Alexa, ask sonos to play ARTIST NAME in the ROOM

Echo responds:

"this command does not work unless you set default line in"

The logs for that are:

2017-01-31T15:40:15.017Z	8ec41070-e7cb-11e6-91de-bb47b0a2912d	{ [AccessDeniedException: User: arn:aws:sts::566400517143:assumed-role/lambda_basic_execution/sonosmainEU is not authorized to perform: dynamodb:ListTables on resource: *]
message: 'User: arn:aws:sts::566400517143:assumed-role/lambda_basic_execution/sonosmainEU is not authorized to perform: dynamodb:ListTables on resource: *',
code: 'AccessDeniedException',
time: Tue Jan 31 2017 15:40:15 GMT+0000 (UTC),
requestId: 'VVTPTL273LN18U8Q5I5POJCPHBVV4KQNSO5AEMVJF66Q9ASUAAJG',
statusCode: 400,
retryable: false,
retryDelay: 0 } 'AccessDeniedException: User: arn:aws:sts::566400517143:assumed-role/lambda_basic_execution/sonosmainEU is not authorized to perform: dynamodb:ListTables on resource: *\n at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:43:27)\n at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)\n at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\n at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\n at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\n at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\n at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)\n at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)'

Thanks in advance.

**Comment by pheintzelman** [comment]
These are too separate things. 

This skill does not currently have an open state, so you can say "Alexa open Sonos" or  "Alexa ask sonos" 
"Alexa ask sonos" works if you say the rest of the utterance.

The second issue is it is picking up the PlayInRoomIntent by mistake see other issue

Your log also shows you are not able to connect to dynamoDb which is what the advanced mode uses. I would start by tracking that down or turning advanced mode off.

**Comment by jdrussell78** [comment]
Thanks.

So I have removed the advanced mode.  Understood that.

I don't understand where I remove the playinroomintent from.  Accoridng to https://github.com/rgraciano/echo-sonos/issues/105, I need to remoive the lineinintent.  I tried this, but then the json was invalid, so I copied and pasted the json again for the intents from ascratch and pasted this back to how it was and now the interaction model errors while saving.

This I don't understand as it is exactly the same as I left it in the first place, why won't it save ?

Bit more confused than when I started on this one.

**Comment by jdrussell78** [comment]
and now I am trying to revert back to how it was exactly with the utterances and the intents and I get this error


Error: Failed building the interaction model.


I don't understand this as this is exactly the same as it was before any changes.

**Comment by jdrussell78** [comment]
Ok.

I have sorted out the interaction model problem.

I have removed the LineInIntent and PlayInRoomIntent from the intents schema and the utterances.

When I say:

"Alexa, ask sonos play Glasto 2014 in the Kitchen"

I get an "OK" from Alexa

Nothing plays.

In the logs:


10:45:55
2017-02-01T10:45:55.699Z	9bf10f75-e86b-11e6-a1ef-c388d71a867e	session applicationId: amzn1.ask.skill.b3bcec14-ed4c-435c-a297-2171d16127c5
2017-02-01T10:45:55.699Z	9bf10f75-e86b-11e6-a1ef-c388d71a867e	session applicationId: amzn1.ask.skill.b3bcec14-ed4c-435c-a297-2171d16127c5

10:45:55
2017-02-01T10:45:55.699Z	9bf10f75-e86b-11e6-a1ef-c388d71a867e	dispatch intent = ArtistIntent
2017-02-01T10:45:55.699Z	9bf10f75-e86b-11e6-a1ef-c388d71a867e	dispatch intent = ArtistIntent

10:45:55
2017-02-01T10:45:55.699Z	9bf10f75-e86b-11e6-a1ef-c388d71a867e	MusicIntent received for room kitchen
2017-02-01T10:45:55.699Z	9bf10f75-e86b-11e6-a1ef-c388d71a867e	MusicIntent received for room kitchen

10:45:55
2017-02-01T10:45:55.699Z	9bf10f75-e86b-11e6-a1ef-c388d71a867e	Advanced Mode = false
2017-02-01T10:45:55.699Z	9bf10f75-e86b-11e6-a1ef-c388d71a867e	Advanced Mode = false

10:45:55
2017-02-01T10:45:55.699Z	9bf10f75-e86b-11e6-a1ef-c388d71a867e	Sending HTTP request to: /preset/artist%3Aglasto%202014
2017-02-01T10:45:55.699Z	9bf10f75-e86b-11e6-a1ef-c388d71a867e	Sending HTTP request to: /preset/artist%3Aglasto%202014

10:45:55
END RequestId: 9bf10f75-e86b-11e6-a1ef-c388d71a867e
END RequestId: 9bf10f75-e86b-11e6-a1ef-c388d71a867e

10:45:55
REPORT RequestId: 9bf10f75-e86b-11e6-a1ef-c388d71a867e	Duration: 274.66 ms	Billed Duration: 300 ms Memory Size: 128 MB	Max Memory Used: 27 MB
REPORT RequestId: 9bf10f75-e86b-11e6-a1ef-c388d71a867e	Duration: 274.66 ms	Billed Duration: 300 ms Memory Size: 128 MB	Max Memory Used: 27 MB	

Any idea why nothing plays ?

**Comment by jdrussell78** [comment]
SO it seems like I can control and play controls, which is a step in the right direction.  But asking sonos to play an artist in a room does not work.

**Comment by jdrussell78** [comment]
I have a feeling this is something to do with it, on the requests when i try and initiate playback the HTTP request is:

Sending HTTP request to: /preset/artist%3AMichael%20Jackson

but on the times when i am trying to do volume up, or in my last try to join the kitchen to the livingroom, the HTTP request is different:

Sending HTTP request to: /kitchen/join/living%20room

I am guessing, the preset part of the top HTTP request is the issue?  Just not sure how to resolve it.

**Comment by jdrussell78** [comment]
Ok finally got it working, needed to change the default music service with advanced mode set to true and then change it to spotify.  Managed to get it working in the main now.

@pheintzelman thanks so much for your help.  Really appreciate it.

**Comment by Barbo10** [comment]
Hey! What are the guide to turn on the advance mode? I think are these:

1) On echo-sonos-master/lambda/src/options/options.js:28 change the word false to true
2) repack the 3 files to a zip
3) upload the new zip

it is ok? and where I have to put to use my spotify account?? I dont find that...

Thanks.

**Comment by jdrussell78** [comment]
I don't think you need to change the options.js file at all. I would leave that as it is. 

If you look at the readme you need to add the advanced mode variable to the lambda function config and follow the steps (again in the readme) for configuring dynamodb. 

Once you have done this you'll then be able to change the default music service to Spotify.
