### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sebwinters** [rgraciano/echo-sonos#125]
I'm getting the error when using the supplied test:

`{
  "errorMessage": "Cannot find module './options'",
  "errorType": "Error",
  "stackTrace": [
    "Module._compile (module.js:409:26)",
    "Object.Module._extensions..js (module.js:416:10)",
    "Module.load (module.js:343:32)",
    "Function.Module._load (module.js:300:12)",
    "Module.require (module.js:353:17)"
  ]
}`

And this is what I get from the log file when talking to alexa
`Unable to import module 'index': Error
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/var/task/index.js:9:15)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)`

Any tips?

**Comment by pheintzelman** [comment]
Did you upload options.js?

**Comment by mintile** [comment]
NO, I didn’t. I downloaded the source a few weeks ago but never uploaded anything.


[cid:image002.png@01D282D3.C90E3EB0] Mike Intile
Retail Business Management Systems, Inc.
105 White Oak  Lane Old Bridge, NJ, 08857
40 Worth St. 10th Floor  New York, NY 10013
Phone: (732) 607-7773  Toll Free: (800) 506-4321  Fax: (732) 607-7755
mintile@rbms.com<mailto:mintile@rbms.com>  |  www.rbms.com<http://www.rbms.com/>

**Comment by sebwinters** [comment]
Thanks for your reply. I don't follow. Did I upload?, I followed the instructions, I dont see anything mentioned about uploading options.js

`START RequestId: *** Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/task/index.js:9:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
END RequestId: d80fbbc4-ef0a-11e6-affa-474a3f9dd50c
REPORT RequestId: d80fbbc4-ef0a-11e6-affa-474a3f9dd50c	Duration: 48.11 ms	Billed Duration: 100 ms`

**Comment by sebwinters** [comment]
Ah I got it. In the directory is the file options.example.js. I did not rename it, not the error is resolved. I got another one though...

`{
  "errorMessage": "Cannot read property 'application' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "AlexaSkill.execute (/var/task/AlexaSkill.js:86:62)",
    "exports.handler (/var/task/index.js:831:15)"
  ]
}`

Any idea about this one?
Thanks

**Comment by sebwinters** [comment]
Ah I got it. In the directory the filename is options.example.js. I did not rename it, now the error is resolved. I got another one though... Is does not seem to be able to connect to my server.

`{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "The Lambda service encountered an error: getaddrinfo ENOTFOUND http://*.synology.me:8085/ http://*.synology.me:8085/:5005"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}
`
I forward port 8085 to 5005 and I am amble to reach from outside my network.

**Comment by pheintzelman** [comment]
Make sure you don't include http as part of the host environment var.

Can you hit your endpoint from a browser?

**Comment by sebwinters** [comment]
Thanks. Tried that before indeed. Now again with no luck. Also tried my direct IP. Yes I can reach it from a browser out of my network.

**Comment by sebwinters** [comment]
Ok I think I got it. It is not possible to use another port than 5005. I used a different port and put that in the host var. Code will than put :5005 at the end.

**Comment by pheintzelman** [comment]
@sebwinters you can use a different port but you have to put it in the PORT not HOST
