### ISSUE TITLE
can't get it to play by artist 

### ISSUE THREAD

**Issue by Slepperpon** [rgraciano/echo-sonos#127]
All commands work and alexa says ok but will not let you select artist can only play or pause what was played last

2017-02-13T18:03:05.239Z aae97f09-f216-11e6-8ea9-c1393fa9b2b8 dispatch intent = ArtistIntent 

18:03:05
2017-02-13T18:03:05.239Z aae97f09-f216-11e6-8ea9-c1393fa9b2b8 MusicIntent received for room bedroom 

18:03:05
2017-02-13T18:03:05.239Z aae97f09-f216-11e6-8ea9-c1393fa9b2b8 Advanced Mode = true 

18:03:05
2017-02-13T18:03:05.339Z aae97f09-f216-11e6-8ea9-c1393fa9b2b8 Reading current settings 

18:03:05
2017-02-13T18:03:05.458Z aae97f09-f216-11e6-8ea9-c1393fa9b2b8 room=bedroom newRoom= service=presets newService= 

18:03:05
2017-02-13T18:03:05.459Z aae97f09-f216-11e6-8ea9-c1393fa9b2b8 Sending HTTP request to: /preset/artist%3ANickelback 

18:03:05
END RequestId: aae97f09-f216-11e6-8ea9-c1393fa9b2b8

**Comment by Slepperpon** [comment]
I can type in commands for http and it works just will not work by voice.

**Comment by pheintzelman** [comment]
You need to set a default service.

**Comment by Slepperpon** [comment]
I did set apple as default in the option.js
defaultMusicService: getDefault('DEFAULT_MUSIC_SERVICE', 'apple'), // Supports presets, apple, spotify, deezer, or library

**Comment by Slepperpon** [comment]
I got it working by asking alexa to change music service to apple music now it works the only small problem is if the room you call on has no music playing it just queue the music and will not play it.

**Comment by Slepperpon** [comment]
This is the error i get it will queue the song i ask for but does not play the reply from alex says queued and played.
Error
    at Object.invoke (/home/pi/node_modules/sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:95:10)

**Comment by hernandito** [comment]
I feel like I am close.... I am able to send resume and pasue playback to all my Sonos devices. However it will not respond commands to specific rooms.

My presets.json looks like this:

> 
> {
>   "players": [
>     {
>       "roomName": "bathroom",
>       "volume": 50
>     },
>     {
>       "roomName": "staci office",
>       "volume": 50
>     },
>   ],
>   "playMode": {
>     "shuffle": true,
>     "repeat": "all",
>     "crossfade": false
>   },
>   "pauseOthers": false,
>   "favorite": "My example favorite"
> }

So if I say "**Alexa tell Sonos to play Led Zeppelin in the bathroom**" she says "**OK**" but nothing happens. I do have Zep in my Sonos Music Library, and also in my Plex library. The terminal console does not say anything.

If I say "**Alexa tell Sonos to pause bathroom**", she says "**OK**". But nothing happens and the console shows:

> 2017-02-19T20:01:41.804Z ERROR
> { error: 'action \'bathroom\' not found' }

Please help... I would love to get this fully working. I have been trying for over a week.

My settings.json file is below (renamed to .txt so I can post here): 
[setting.json.txt](https://github.com/rgraciano/echo-sonos/files/786148/setting.json.txt)

Many thanks,

H.

**Comment by pheintzelman** [comment]
@hernandito can you do this command just using the url? It will be url/bathroom/pause you can check the sonos node project to be sure.

Also post your lambda logs.

**Comment by pheintzelman** [comment]
@Slepperpon there is a known bug with advanced mode not starting with the default service so you have to say switch service after install.

**Comment by hernandito** [comment]
@pheintzelman - thank you for replying. I was able to execute the pause command via url. That worked. When going through Alexa, I think this is the errorr code of the command on the Lambda log:

`2017-02-20T14:44:59.052Z 26b2f897-f77b-11e6-b6cd-239b929b5a57 { [AccessDeniedException: User: arn:aws:sts::03xxxxxxxxxxx3:assumed-role/lambda_basic_execution/mySonos is not authorized to perform: dynamodb:ListTables on resource: *]
message: 'User: arn:aws:sts::03xxxxxxxxx3:assumed-role/lambda_basic_execution/mySonos is not authorized to perform: dynamodb:ListTables on resource: *',
code: 'AccessDeniedException',
time: Mon Feb 20 2017 14:44:58 GMT+0000 (UTC),
requestId: 'TOD0ESJK5345TAOKQQR6BH7SNNVV4KQNSO5AEMVJF66Q9ASUAAJG',
statusCode: 400,
retryable: false,
retryDelay: 0 } 'AccessDeniedException: User: arn:aws:sts::03xxxxxxxxxxx3:assumed-role/lambda_basic_execution/mySonos is not authorized to perform: dynamodb:ListTables on resource: *\n at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:43:27)\n at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)\n at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\n at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\n at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\n at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\n at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)\n at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)'`

I do have security enabled, advanced mode, but no SSL. The above is not something I can understand.

Many thanks again!.

H.

**Comment by pheintzelman** [comment]
I haven't done much with advanced mode so this might not be the issue. But I think you need to give lambda permission to use dynamodb. I just saw some instructions for this if I track them down I will add a link.
