### ISSUE TITLE
Using SQS with presets doesn't work with new Presets.json location

### ISSUE THREAD

**Issue by taylorjason** [rgraciano/echo-sonos#128]
I enabled SQS and presets stopped working. I figured out that when using SQS it looks for presets in the root directory instead of the `/presets` folder that has been implemented.  Moving the presets.json file back to the root directory disrupts the auto updating feature so I created a symbolic link to the `/presets/presets.json` file, and that fixed it. Anyone know how to fix the code so that the SQS server requests look for the presets.json in the proper place? Apologies, I am new to JS and this stuff.

**Comment by pheintzelman** [comment]
@taylorjason what does it show in your sqs console when you have the issue? 
The sqs server should call yoururl:port/preset/rock the same thing as not using sqs. So the sonos node server should do the same action. 

The only possibility I can think of is that it ends up with extra slashes or too few.

**Comment by rgraciano** [comment]
closed due to inactivity
