### ISSUE TITLE
Lambada test Issue

### ISSUE THREAD

**Issue by smith-l** [rgraciano/echo-sonos#130]
Hi all,

I have a problem with configuring the Lambada, I have uploaded the 3 files as directed but when selecting test I see the following error:

{
  "errorMessage": "Cannot read property 'application' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "AlexaSkill.execute (/var/task/AlexaSkill.js:86:62)",
    "exports.handler (/var/task/index.js:831:15)"
  ]
}

Please can anyone offer any advise?

cheers.

**Comment by stephanstricker** [comment]
I get the exact same error. Did you find out what was wrong?

Stephan

**Comment by stephanstricker** [comment]
Found the problem myself. I copied the text from the textbox instead of using lambda/play_intent_testreq.json
