### ISSUE TITLE
 Error: Please make sure that "Alexa Skills Kit" is selected for the event source type of ...

### ISSUE THREAD

**Issue by jzajac2** [rgraciano/echo-sonos#138]
When connecting my Alexa Skill to my AWS Lambda by copying in the ARN I get a validation error in AWS console: 

`
Error: Please make sure that "Alexa Skills Kit" is selected for the event source type of arn:aws:lambda:us-east-1:{blahblahmysecretfunc}`

I'm definitely copying/pasting in the correct ARN.

**My question here is: is the 'event source type' in the error message referring to something configured in the lambda\src I zipped and uploaded to my Lambda in AWS? Or rather I configured my skill wrong?**

Just in case, here is my zip structure:
![image](https://cloud.githubusercontent.com/assets/101703/23584577/efc03420-012a-11e7-994d-641d553f5b97.png)

Also - the readme says this step is in the 'Skills Information' section however for me it is later in the Configuration section so may want to update the readme...although I'm sure they change their dashboard/manager UIs frequently so keeping is a PITA:

![image](https://cloud.githubusercontent.com/assets/101703/23584585/1541e978-012b-11e7-94e7-4f577a7342a3.png)

**Comment by jzajac2** [comment]
Whoops. Had to add Alexa Skills Kit as trigger in my lambda

**Comment by ManivannanMurugavel** [comment]
Please create a lambda function with alexa skill kit

**Comment by rathisoft** [comment]
oh yeah.. Had to add Alexa Skills Kit as trigger in my lambda

**Comment by gregsadetsky** [comment]
If anybody stumbles upon this, and wants to do it using the AWS CLI, you can use [this](https://stackoverflow.com/a/39514119/426790) solution, which calls `aws lambda add-permission`.
