### ISSUE TITLE
Do playlists support spotify playlists?

### ISSUE THREAD

**Issue by HughMacdonald** [rgraciano/echo-sonos#141]
I'm not sure if I should be able to, but I can't get a Spotify playlist to play using this skill.

If I say "Alexa, ask Sonos to play playlist Discover Weekly in Living Room", it responds with "queued and started Discover Weekly", but then just plays whatever was previously queued up.

If I check the output on my server, it has said:

    2017-03-14T20:23:11.915Z ERROR 
      Error: Playlist not found
        at /home/ubuntu/node_modules/sonos-discovery/lib/prototypes/Player/replaceWithPlaylist.js:13:15
        at process._tickDomainCallback (node.js:411:9)

**Comment by pheintzelman** [comment]
It looks for a sonos playlist. To add support for spotify playlist this feature would need to be added to https://github.com/jishi/node-sonos-http-api please create an issue there.
