### ISSUE TITLE
A Little Help with Presets.json

### ISSUE THREAD

**Issue by hernandito** [rgraciano/echo-sonos#142]
Hi,

I was able to get he Sonos API working fine... but I can't control it via the Echo all that well. The only commands that work are "Alexa, tell Sono to Pause/Resume All".  The individual rooms do not work, nor the Favorites, Arttists, etc.

I have so far 2 Playlists in my Favorites. "Black Angels" and "Psychodelic". What I get when I go to my server web interface: http://192.168.1.201:5005/zones, I get the following:

http://pastebin.com/FiWzmHwW

Can someone please help me to configure the presets.json so this can get full functionality...? I have been trying for weeks to get this working. I would be happy to write a how-to guide on configuring this to help  others afterwards.

Many thanks,

H.

**Comment by petebanham** [comment]
Hi, I am by no means an expert but I have mine working without doing anything to presets.json as it doesn't seem to be needed for the skill to work. Have you updated the Custom Slot Types in the Alexa Skill? I added all my favourites to the PRESETS slot type and amended the ROOMS to match my speaker names. Also in the Lambda settings,  on the code page,  have you defined the default music service you want to use? I would also start with advanced mode off here. With fault finding I would start by making sure you can start rooms and music etc directly on the node sever using a local web browser first. If that works then try from the skill service simulationer (this removes any voice understanding issues) and the other place to look is the Lambda service logs as the errors there can often point to the problem. Sorry this isn't a specific fix, more some trouble shooting ideas that may help.  Pete

**Comment by pheintzelman** [comment]
As @petebanham said the presets.json isn't needed for this to work. That file is only if you want to use presets.
