### ISSUE TITLE
Mostly there, but spotify is still not working

### ISSUE THREAD

**Issue by evansgo** [rgraciano/echo-sonos#143]
Thanks so much for this, its mostly working really well....

I have a UK setup and almost everything is now working, (Playlists, Library etc), but the sonos will still not play spotify.

I am getting Alexa saying all is fine but no actual music comes out..

The logfile shows this:-
2017-03-23T12:51:31.710Z	6917b789-0fc7-11e7-9796-a7e3ab08854a	Call to 'http://xxxxxx.hopto.org:5005/study/musicsearch/spotify/song/artist:Adele' failed

2017-03-23T12:51:31.710Z	6917b789-0fc7-11e7-9796-a7e3ab08854a	Error: Failed to retrieve data, status code: 500
at ClientRequest.lib.get (/var/task/sonosProxy/httpClient.js:13:17)
at ClientRequest.g (events.js:291:16)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
at Socket.socketOnData (_http_client.js:363:20)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at readableAddChunk (_stream_readable.js:176:18)
 

Can someone point me in the right direction?
Thanks very much....

**Comment by pheintzelman** [comment]
try hitting http://xxxxxx.hopto.org:5005/study/musicsearch/spotify/song/artist:Adele directly that url looks correct 

500 is a server error coming from the sonos node app, make sure it is running

**Comment by evansgo** [comment]
Thanks. Yes now I'm testing more its all looking a bit flakey :)
The join command fails frequently, although the ungroup seems to work fine, odd things like that. 
I can play from the library fine, but as soon as I switch to spotify nothing happens and I get the error. As you say its looking very much like the node app and probably because of how I installed it...

When I ran the npm install https://github.com/jishi/node-sonos-http-api command it didn't work correctly...
So I downloaded the zip, unzipped and put it into my /users/G/ folder then made the changes and carried on and it all seemed to work, the http://yourserverip:5005/zones works fine internally and externally but still something is not quite right there. 
I've just tried reinstalling but am getting the error below...

I'll keeep trying but if you can see anything obvious, please shout - most likely something basic as this is not my area of expertise at all....

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'https://github.com/jishi/node-sonos-http-api' ]
2 info using npm@3.10.10
3 info using node@v6.10.0
4 verbose config Skipping project config: /Users/G/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData https://github.com/jishi/node-sonos-http-api
9 silly fetchOtherPackageData https://github.com/jishi/node-sonos-http-api
10 silly cache add args [ 'https://github.com/jishi/node-sonos-http-api', null ]
11 verbose cache add spec https://github.com/jishi/node-sonos-http-api
12 silly cache add parsed spec Result {
12 silly cache add   raw: 'https://github.com/jishi/node-sonos-http-api',
12 silly cache add   scope: null,
12 silly cache add   escapedName: null,
12 silly cache add   name: null,
12 silly cache add   rawSpec: 'https://github.com/jishi/node-sonos-http-api',
12 silly cache add   spec: 'git+https://github.com/jishi/node-sonos-http-api.git',
12 silly cache add   type: 'hosted',
12 silly cache add   hosted:
12 silly cache add    { type: 'github',
12 silly cache add      ssh: 'git@github.com:jishi/node-sonos-http-api.git',
12 silly cache add      sshUrl: 'git+ssh://git@github.com/jishi/node-sonos-http-api.git',
12 silly cache add      httpsUrl: 'git+https://github.com/jishi/node-sonos-http-api.git',
12 silly cache add      gitUrl: 'git://github.com/jishi/node-sonos-http-api.git',
12 silly cache add      shortcut: 'github:jishi/node-sonos-http-api',
12 silly cache add      directUrl: 'https://raw.githubusercontent.com/jishi/node-sonos-http-api/master/package.json' } }
13 verbose addRemoteGit caching https://github.com/jishi/node-sonos-http-api
14 verbose addRemoteGit git+https://github.com/jishi/node-sonos-http-api.git is a repository hosted by github
15 silly tryClone cloning git+https://github.com/jishi/node-sonos-http-api.git via git+https://github.com/jishi/node-sonos-http-api.git
16 verbose tryClone git-https-github-com-jishi-node-sonos-http-api-git-59bf2b22 not in flight; caching
17 verbose correctMkdir /Users/G/.npm/_git-remotes correctMkdir not in flight; initializing
18 info git [ 'config', '--get', 'remote.origin.url' ]
19 silly validateExistingRemote git+https://github.com/jishi/node-sonos-http-api.git remote.origin.url: https://github.com/jishi/node-sonos-http-api.git
20 verbose validateExistingRemote git+https://github.com/jishi/node-sonos-http-api.git is updating existing cached remote /Users/G/.npm/_git-remotes/git-https-github-com-jishi-node-sonos-http-api-git-59bf2b22
21 info git [ 'fetch', '-a', 'origin' ]
22 verbose updateRemote git fetch -a origin (https://github.com/jishi/node-sonos-http-api.git)
23 verbose correctMkdir /Users/G/.npm/_git-remotes correctMkdir not in flight; initializing
24 verbose setPermissions git+https://github.com/jishi/node-sonos-http-api.git set permissions on /Users/G/.npm/_git-remotes/git-https-github-com-jishi-node-sonos-http-api-git-59bf2b22
25 verbose resolveHead git+https://github.com/jishi/node-sonos-http-api.git original treeish: master
26 info git [ 'rev-list', '-n1', 'master' ]
27 silly resolveHead git+https://github.com/jishi/node-sonos-http-api.git resolved treeish: a1817a1194ac24f8ef6d6551959cdcbfcdad9a23
28 verbose resolveHead git+https://github.com/jishi/node-sonos-http-api.git resolved Git URL: git+https://github.com/jishi/node-sonos-http-api.git#a1817a1194ac24f8ef6d6551959cdcbfcdad9a23
29 silly resolveHead Git working directory: /var/folders/05/25js2z5123xdth5jmrqkyp2h0000gn/T/npm-14892-0693ded7/git-cache-a27d797d/a1817a1194ac24f8ef6d6551959cdcbfcdad9a23
30 info git [ 'clone',
30 info git   '/Users/G/.npm/_git-remotes/git-https-github-com-jishi-node-sonos-http-api-git-59bf2b22',
30 info git   '/var/folders/05/25js2z5123xdth5jmrqkyp2h0000gn/T/npm-14892-0693ded7/git-cache-a27d797d/a1817a1194ac24f8ef6d6551959cdcbfcdad9a23' ]
31 verbose cloneResolved git+https://github.com/jishi/node-sonos-http-api.git clone Cloning into '/var/folders/05/25js2z5123xdth5jmrqkyp2h0000gn/T/npm-14892-0693ded7/git-cache-a27d797d/a1817a1194ac24f8ef6d6551959cdcbfcdad9a23'...
31 verbose cloneResolved done.
32 info git [ 'checkout', 'a1817a1194ac24f8ef6d6551959cdcbfcdad9a23' ]
33 verbose checkoutTreeish git+https://github.com/jishi/node-sonos-http-api.git checkout Note: checking out 'a1817a1194ac24f8ef6d6551959cdcbfcdad9a23'.
33 verbose checkoutTreeish
33 verbose checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
33 verbose checkoutTreeish changes and commit them, and you can discard any commits you make in this
33 verbose checkoutTreeish state without impacting any branches by performing another checkout.
33 verbose checkoutTreeish
33 verbose checkoutTreeish If you want to create a new branch to retain commits you create, you may
33 verbose checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
33 verbose checkoutTreeish
33 verbose checkoutTreeish   git checkout -b <new-branch-name>
33 verbose checkoutTreeish
33 verbose checkoutTreeish HEAD is now at a1817a1... Add equalizer info to state response
34 info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
35 verbose updateSubmodules git+https://github.com/jishi/node-sonos-http-api.git submodule update
36 verbose addLocalDirectory /Users/G/.npm/sonos-http-api/1.4.1/package.tgz not in flight; packing
37 verbose correctMkdir /Users/G/.npm correctMkdir not in flight; initializing
38 verbose tar pack [ '/Users/G/.npm/sonos-http-api/1.4.1/package.tgz',
38 verbose tar pack   '/var/folders/05/25js2z5123xdth5jmrqkyp2h0000gn/T/npm-14892-0693ded7/git-cache-a27d797d/a1817a1194ac24f8ef6d6551959cdcbfcdad9a23' ]
39 verbose tarball /Users/G/.npm/sonos-http-api/1.4.1/package.tgz
40 verbose folder /var/folders/05/25js2z5123xdth5jmrqkyp2h0000gn/T/npm-14892-0693ded7/git-cache-a27d797d/a1817a1194ac24f8ef6d6551959cdcbfcdad9a23
41 verbose addLocalTarball adding from inside cache /Users/G/.npm/sonos-http-api/1.4.1/package.tgz
42 verbose correctMkdir /Users/G/.npm correctMkdir not in flight; initializing
43 verbose addRemoteGit data._from: git+https://github.com/jishi/node-sonos-http-api.git
44 verbose addRemoteGit data._resolved: git+https://github.com/jishi/node-sonos-http-api.git#a1817a1194ac24f8ef6d6551959cdcbfcdad9a23
45 silly cache afterAdd sonos-http-api@1.4.1
46 verbose afterAdd /Users/G/.npm/sonos-http-api/1.4.1/package/package.json not in flight; writing
47 verbose correctMkdir /Users/G/.npm correctMkdir not in flight; initializing
48 verbose afterAdd /Users/G/.npm/sonos-http-api/1.4.1/package/package.json written
49 silly install normalizeTree
50 silly loadCurrentTree Finishing
51 silly loadIdealTree Starting
52 silly install loadIdealTree
53 silly cloneCurrentTree Starting
54 silly install cloneCurrentTreeToIdealTree
55 silly cloneCurrentTree Finishing
56 silly loadShrinkwrap Starting
57 silly install loadShrinkwrap
58 silly loadShrinkwrap Finishing
59 silly loadAllDepsIntoIdealTree Starting
60 silly install loadAllDepsIntoIdealTree
61 silly rollbackFailedOptional Starting
62 silly rollbackFailedOptional Finishing
63 silly runTopLevelLifecycles Finishing
64 silly install printInstalled
65 verbose stack Error: Refusing to install sonos-http-api as a dependency of itself
65 verbose stack     at checkSelf (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:53:14)
65 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
65 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
65 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
65 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/validate-args.js:16:5
65 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
65 verbose stack     at Array.forEach (native)
65 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
65 verbose stack     at Array.forEach (native)
65 verbose stack     at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
66 verbose cwd /Users/G
67 error Darwin 14.5.0
68 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/jishi/node-sonos-http-api"
69 error node v6.10.0
70 error npm  v3.10.10
71 error code ENOSELF
72 error Refusing to install sonos-http-api as a dependency of itself
73 error If you need help, you may report this error at:
73 error     <https://github.com/npm/npm/issues>
74 verbose exit [ 1, true ]

**Comment by pheintzelman** [comment]
when you did the npm install for the node server did you do _npm install --production_

**Comment by evansgo** [comment]
I didn't at first, but I'm almost certain that I have done it since as I read it somewhere else. I'll go try it again though, I'm assuming that it won't hurt doing it twice...

**Comment by evansgo** [comment]
Just in case I am doing something totally stupid (I may well be!) I am downloading the zip, you pointed to, unzipping it to my user directory, opening terminal, CD ing to the directory with 'cd /Users/g/node-sonos-http-api', then running npm install --production, then adding the settings file and then finally running npm start.

Most things are working and the local library works fine, but spotify just will not work. I have tried calling it directly so its (as you said) nothing to do with Alexa or the cloud services or port mapping, it is local to npm. Spotify works perfectly using the 'real' sonos app (not running at the same time) but it returns the same no matter if I call an album, an artist or a song.

**Comment by pheintzelman** [comment]
What you have in the first paragraph is correct. If it is not working when you call it directly you should open an issue in the node-sonos project.
