### ISSUE TITLE
Error when fetching favorites when using node v7.7.4

### ISSUE THREAD

**Issue by jzajac2** [rgraciano/echo-sonos#144]
Not sure if this is directly related to node-sonos-http-api rather than this project however I noticed when installing latest stable node (currently v7.7.4) utterances such as "Alexa, tell sonos to play favorites Deep Focus" it would respond OK however I would see "Error when fetching favorites" in the debug output.

**Comment by pheintzelman** [comment]
Try doing this command through the url. If that doesn't work open an issue in node-sonos-http-api
