### ISSUE TITLE
Help finding options.example.js

### ISSUE THREAD

**Issue by loftgren** [rgraciano/echo-sonos#145]
Can someone please tell me where to find the file options.example.js? Thanks very much in advance!

**Comment by loftgren** [comment]
Sorry, I actually know where options.example.js is located... what i really need is to be able to find options.js.  I assume I am looking locally?  Step 5 is killing me! Any help is greatly appreciated!

**Comment by GregRocket** [comment]
@loftgren Just rename the file **options.example.js** to **options.js**
