### ISSUE TITLE
'Error: Failed building the interaction model.'

### ISSUE THREAD

**Issue by bccmini247** [rgraciano/echo-sonos#146]
Having this issue in the Alexa Skill creation area. Any help?

**Comment by pheintzelman** [comment]
Did you add all the slot types?

**Comment by jameshiscott** [comment]
Same problem. I have all the Slots added (presets, rooms, sxmchannels, sxmstations, services, toggles, names)

**Comment by jameshiscott** [comment]
fixed it with this:

Note: if you're in the UK or Germany, Amazon's support for band names and songs may not be available yet. In that case, replace anywhere you see "AMAZON.MusicGroup", "AMAZON.MusicRecording", and "AMAZON.MusicAlbum" with the word "NAMES".
