### ISSUE TITLE
Changing service to Spotify has issue with Capitalisation

### ISSUE THREAD

**Issue by Progression** [rgraciano/echo-sonos#147]
I can't use Spotify as the music service as the system is the following URL:

http://XXX.yyy.zzz:5005/study/musicsearch/Spotify/song/artist:Ben%20Harper

Notice that the service Spotify has a capital "S". If its a lowercase "s" it works fine.

I set the service to Spotify using the voice command and the Lambda request sent skill capitialises Spotify:

```
{
  "session": {
    "sessionId": "SessionId.0b9a695d-e6f2-41d8-a931-26edc2b4202e",
    "application": {
      "applicationId": "xxxx"
    },
    "attributes": {},
    "user": {
      "userId": "xxx"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.ab11dbca-2fdb-4f44-9028-76cc2ac21ee0",
    "locale": "en-GB",
    "timestamp": "2017-04-02T09:57:09Z",
    "intent": {
      "name": "ChangeServiceIntent",
      "slots": {
        "Service": {
          "name": "Service",
          "value": "Spotify"
        }
      }
    }
  },
  "version": "1.0"
}
```

It would seem that all the code after that never converts the value to a lowercase value and the service is stored with this capitalised version. This then is used when building the url later. If I manually test the Lambda service with this same JSON but change the "Spotify" to "spotify" it will work correctly later on.

Heres a log when I change the service to spotify:

```
2017-04-02T09:56:46.679Z	aecf0d37-178a-11e7-ba64-9bb528c8e17c	Update of current defaults succeeded:
{
    "Attributes": {
        "currentMusicService": "Spotify"
    }
}`
```

And when I change the service to apple (which works fine)

```
2017-04-02T09:57:10.164Z	bcd5996d-178a-11e7-9f1a-e536d85e6833	Update of current defaults succeeded:
{
    "Attributes": {
        "currentMusicService": "apple"
    }
}
```

Should the code be converting this value to lowercase at some point?

**Comment by pheintzelman** [comment]
Nice investigation.

**Comment by chrismcc409** [comment]
I think this is in the changeCurrent function, I changed as below to achieve this;
values = {":r":room, ":s":service};
to
values = {":r":room, ":s":service.toLowerCase()};

and
values = {":s":service};
to
values = {":s":service.toLowerCase()};

**Comment by rgraciano** [comment]
Thanks for the report! I added the fix suggested by @chrismcc409
