### ISSUE TITLE
Feature Request: Add / Remove Groups

### ISSUE THREAD

**Issue by ookami85** [rgraciano/echo-sonos#16]
Awesome work! Will you be incorporating the add / remove from group feature from node-sonos-http-api
 into echo-sono for voice control?

**Comment by rgraciano** [comment]
Sure, I can take a look at this

**Comment by rwupson** [comment]
This would be a great add - I did notice that there is a group.js in the lib/actions folder - are there specific commands?

**Comment by ookami85** [comment]
I just wanted to check in on this. It would be beyond awesome to have this feature. Your work is greatly appreciated.

**Comment by rgraciano** [comment]
Sorry, I'm very busy at work this month, but I'll try to take a crack at this sometime in the next couple of weeks

**Comment by ookami85** [comment]
No worries. If there's any way I can help, please let me know.

**Comment by lemketron** [comment]
Would it be possible to have a variation of join which does not requires PlayingRoom?  That is, if I'm the only one home, and only one room is playing, it would be nice to be able to say something like "add Living Room" or "add Kitchen" without having to also specify the playing room.

This would be a nice enabler to combine with some sort of (Bluetooth or other) presence detection that might automatically add a room as you walk around the house.

I don't know if the code would have to query Sonos to see what room(s) are playing, but presumably if only one room (or group) is playing, then PlayingRoom should be optional as the default should be to add to the already playing room.

**Comment by subinacls** [comment]
exactly what i would be interested in as well, being the only person at
home while watching TV/Movies/Video games it would be nice to add in
speakers to the playing group or remove as needed.

For example:

Alexa, tell sonos to play rock party mode


On Thu, May 5, 2016 at 5:55 PM, Steve Lemke <notifications@github.com>
wrote:

> Would it be possible to have a variation of join which does not requires
> PlayingRoom? That is, if I'm the only one home, and only one room is
> playing, it would be nice to be able to say something like "add Living
> Room" or "add Kitchen" without having to also specify the playing room.
>
> This would be a nice enabler to combine with some sort of (Bluetooth or
> other) presence detection that might automatically add a room as you walk
> around the house.
>
> I don't know if the code would have to query Sonos to see what room(s) are
> playing, but presumably if only one room (or group) is playing, then
> PlayingRoom should be optional as the default should be to add to the
> already playing room.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rgraciano/echo-sonos/issues/16#issuecomment-217313065>
>



-- 
Research is the key to unlock knowledge -

      OSCE - Offensive-Security Certified Expert
      OSCP - Offensive-Security Certified Professional
      OSWP - Offensive-Security Wireless Professional
      GPEN - SANS560 General Pentester

**Comment by rgraciano** [comment]
@lemketron, @subinacls - there's a general need for coming up with a way to default act on the only playing system without a PlayingRoom parameter.  As you guessed, it would require querying the Sonos system to find the currently playing room and then default acting on it.  I opened #27 to track.
