### ISSUE TITLE
AccessDeniedException in Lambda

### ISSUE THREAD

**Issue by igen27** [rgraciano/echo-sonos#162]
I get constantly this error message in CloudWatch, when i invoke commands to my sonos. The test in AWS runs smooth, everything is up on my homeserver and listening to port 5005 but Alexa says "there was a problem retrieving your answer from the skill". I have no clue, how can i fix this (is not authorized to perform: dynamodb:ListTables on resource: *)

![errormessage](https://cloud.githubusercontent.com/assets/11257148/25860529/1d992e02-34e2-11e7-825d-dfd112a3e6e5.jpg)

**Comment by jplourde5** [comment]
You need to add the dynamodb permission. Follow the proxy instructions very closely.
