### ISSUE TITLE
AWS Lambda account ISN'T free !

### ISSUE THREAD

**Issue by HananeAfoukass** [rgraciano/echo-sonos#163]
I'm trying to create an AWS Lambda account but it isn't free. I keep being asked for my credit card number or some kind of paiement. What shall I do ?

**Comment by nackie99** [comment]
That's because only one tier is free, the details are needed for if you exceed that. eg go over 1,000,000 requests or 3 million seconds of computer time.

**Comment by jplourde5** [comment]
You have to use a CC to open an account. It will not be charged anything unless you exceed a free tier or consume a service that doesn't have a free tier. You pay for what you use. For personal use, it is not likely that you would ever exceed the Lambda free tier, so you will not get charged.
