### ISSUE TITLE
Music Stations Presets

### ISSUE THREAD

**Issue by GregRocket** [rgraciano/echo-sonos#25]
I have several Amazon Music and Pandora Stations in my Sonos Favorites. I also have several Sonos Playlists. 

If I have Alexa "tell sonos to play MYFAVORITE" and the favorite is a playlist, sonos will group the rooms I've setup in presets.json, and starts playing in all the rooms. This works correctly.

If I have Alexa "tell sonos to play MYFAVORITE" and the favorite is a streaming music station, amazon or pandora, music will only be sent to the first room in the preset. No grouping or un-grouping of the rooms happens.

**Comment by rgraciano** [comment]
Depends on: https://github.com/jishi/node-sonos-http-api/issues/192
