### ISSUE TITLE
Grouping and playing favorites don't work for me

### ISSUE THREAD

**Issue by mojopong** [rgraciano/echo-sonos#31]
I've been having problems with grouping my players in the house. I have 2 players and when I say to group them the music that was playing on one just stops and when I then open the app I do not see them grouped. Then I tell it to resume it continues playing on the original it was playing on. Also when I say to play a favorite (Pandora or Google music) station it just says ok and nothing happens. I'm more concerned with the grouping but being able to use both would be cool. Thanks to anyone that can help.

**Comment by GregRocket** [comment]
@mojopong Presets don't work correctly with streaming music sources like Pandora, Amazon etc. Presets should work if your favorite is a playlist of mp3s. It is a bug with node-sonos-http-api and will not be fixed until the beta version becomes a general release.

**Comment by mojopong** [comment]
@gregrocket thanks that's good to know. How about the grouping of speakers?

**Comment by GregRocket** [comment]
@mojopong Try "tell sonos to **join** ROOM to ROOM "
See if that does what you expect.

**Comment by GregRocket** [comment]
Sorry should have read your post more carefully. :-)

Try "tell sonos to **join** ROOM to OTHERROOM"
See if that does what you want.

**Comment by GregRocket** [comment]
@mojopong Sorry should have read your post more carefully. :-)

Try "tell sonos to join ROOM to OTHERROOM"
See if that does what you want.

**Comment by GregRocket** [comment]
@mojopong Sorry should have read your post more carefully. :-)

Try "tell sonos to join ROOM to OTHERROOM"
See if that does what you want.

**Comment by GregRocket** [comment]
@mojopong Sorry should have read your post more carefully.

Try "tell sonos to join ROOM to OTHERROOM"
See if that does what you want.

**Comment by GregRocket** [comment]
@mojopong  Sorry should have read your post more carefully. :-)

Try "tell sonos to join ROOM to OTHERROOM"
See if that does what you want.

**Comment by GregRocket** [comment]
@mojopong Sorry should have read your post more carefully. :-)

Try "tell sonos to **join** ROOM to OTHERROOM"
See if that does what you want.

**Comment by GregRocket** [comment]
@mojopong Sorry should have read your post more carefully. :-)

Try "tell sonos to join ROOM to OTHERROOM"
See if that does what you want.

**Comment by mojopong** [comment]
guess you hit comment a few times or the systems buggy ;) i tried what you suggested and whats playing in the living room will not start playing in the basement when i open the app on my phone i do not see the speakers pairing at all but the echo responds with OK. Does something need to be already playing on the 2nd speaker for it to work? was anything in the presets file supposed to be changed? all i changed was put the names of my speakers in there instead of what was already in there.

**Comment by GregRocket** [comment]
Start music playing in Living Room. If music is not playing in living room joining will not start music when joined with basement/

Try "tell sonos to join BASEMENT to LIVING ROOM" 
This should work.

This has nothing to do with preset.json. A preset can join rooms, select and play a favorite with one command.

**Comment by mojopong** [comment]
still no bueno. i had music playing in living room i told it to join basement to living room the music just kept playing in the living room and nothing happend in the basement. i tried starting music in the basement via the sonos app on my phone and pausing it then joining them together same result. I tried saying the reverse living room to basement and they both went blank in the app and neither was playing then. At least the resume and pause commands work :)

**Comment by GregRocket** [comment]
Did you do this update?

https://github.com/rgraciano/echo-sonos/tree/master/echo

**Comment by GregRocket** [comment]
You could try this preset.json and test if your rooms combine. Put your room names in. Save the preset.json, copy to your server, restart your server. Issue command "tell sonos to play players" The rooms should group and play whatever is in the queue

If this does not combine your rooms my guess it is something with your setup.

**{
    "players": {
      "players": [
		{ "roomName": "Living Room", "volume": 50},
                { "roomName": "Basement", "volume": 50}
      ],
      "pauseOthers": true 
    }
}**

**Comment by mojopong** [comment]
I started using this skill around ten day ago so I'm assuming I was using the updated info you mentioned. When I create a new preset file with what you had put it still didn't work. In the message you said I should out in my room names? Which it looks like you did already so I'm assuming I just take what you said and replace that file with the presets file I had before in there.
I think part of it might be the speaker but then when I just want to resume or pause the music in the basement it works. Just grouping is what is weird because if something is playing down there and I try to group it whatever was playing is cleared from the player as playing, hope that makes sense.

**Comment by GregRocket** [comment]
Did you shut down npm and restart? Do the volumes change per the preset?

That preset should work. I have been using presets for some time and they work fine (unless you are calling a music station Favorite. Then the grouping will not happen.)

I am at a loss as to what is preventing your rooms from grouping.

**Comment by mojopong** [comment]
I did try shutting down and restarting....question I've been testing while playing a Pandora and a Google music station. Never tried while playing a local file as i don't have any on hand is that why this grouping isn't working? Does it (grouping) only work with local files or playlists too?

**Comment by rgraciano** [comment]
@mojopong - it's buggy in the older version of sonos-http-api, but you might try beta testing the new version.

**Comment by rgraciano** [comment]
@mojopong - closing this; please reopen if it works in node-sonos-http-api but not echo-sonos
