### ISSUE TITLE
Echo Dot?

### ISSUE THREAD

**Issue by smwilson** [rgraciano/echo-sonos#35]
Hi, can you please tell me if this will work with the Echo Dot?
Thanks,
Susan

**Comment by GregRocket** [comment]
@smwilson If you follow the instructions here, then yes it will work with the echo dot, tap and echo. First you will need to setup everything as explained at **echo-sonos**. You can then do a test run, without buying a dot, and see if this does what you want. You will need an Amazon account though. Go here https://echosim.io/welcome for an echo simulator.

**Comment by smwilson** [comment]
Thanks! I’ve been making a lot of progress on this, so I will go ahead and order the Dot. I’m a retired techie, and this just tweeks my techie mind. Enjoying all of it.

Susan

> On Jun 10, 2016, at 5:28 PM, GregRocket <notifications@github.com> wrote:
> 
> @smwilson <https://github.com/smwilson> If you follow the instructions here, then yes it will work with the echo dot, tap and echo. First you will need to setup everything as explained at echo-sonos. You can then do a test run, without buying a dot, and see if this does what you want. You will need an Amazon account though. Go here https://echosim.io/welcome <https://echosim.io/welcome> for an echo simulator.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/rgraciano/echo-sonos/issues/35#issuecomment-225319077>, or mute the thread <https://github.com/notifications/unsubscribe/AG0wlgciZ8PN3E1etrzFZaR332cTVTMRks5qKfMqgaJpZM4IzUmK>.
> 

“ Education is that which remains when one has forgotten everything he learned in school. ”
— Albert Einstein
