### ISSUE TITLE
Play Echo and Sonos Speakers Simultaneously?

### ISSUE THREAD

**Issue by bejota** [rgraciano/echo-sonos#36]
I appreciate all of your work here. Is it possible to play the Echo and Sonos speakers in unison? I have a Sonos Play:1 and an Amazon Echo. I am not familiar with their protocols. I apologize for starting an issue just to ask a question, but this is clearly the most advanced work in the area.

**Comment by kshartman** [comment]
I don't think you currently can't do this with software but you could connect a computer (or something) to the line out of a sonos connect.  Pair the computer using bluetooth to the echo.  Whenever that connect plays, the sound would travel through the line out to play on the computer (which doesn't have to have speakers) which would then travel through the bluetooth to play on the echo.  A raspberry pi with a line in and bluetooth radio could do this, effectively its a bluetooth gateway between the sonos connect and the echo.

**Comment by bejota** [comment]
Ahh, clever idea.

**Comment by tlc** [comment]
The Sonos protocol for keeping them in sync is proprietary and has not been cracked.  Many people would love to have their computer audio, for example, synced with their Sonos.
