### ISSUE TITLE
lamda time out every other request

### ISSUE THREAD

**Issue by kshartman** [rgraciano/echo-sonos#37]
For some reason the lamda has starting timing out every other request.  I put debug statements in the node server on my machine and its not getting the request.  I put a trace filter on my firewall and I can confirm the request  never hits the firewall when this happens.  I am starting to debug the lambda but I wanted to know if anyone else had this problem.

**Comment by kshartman** [comment]
So the lambda is getting the playintent.  On the first call it works.  On the second call the httpreq is sent so far as the code is concerned but it never arrives.

**Comment by kshartman** [comment]
Well as stupid as it may sound, if I do the following(call httpreq twice) it always works. Something is going wrong in httpreq so that every other call does not actually send the request and the lambda times out.

   PlayIntent: function (intent, session, response) {
        console.log("PlayIntent received");
        options.path = '/preset/' + encodeURIComponent(intent.slots.Preset.value.toLowerCase());
        httpreq(options, function(error) {
            console.log("debug: " + JSON.stringify(error));
            genericResponse(error, response);
        });
        httpreq(options, function(error) {
            console.log("debug: " + JSON.stringify(error));
            genericResponse(error, response);
        });
        console.log("debug: playintent done");
    },

**Comment by kshartman** [comment]
So whats happening is literally every other request to httpreq does not callback. I put debug statements so you can see.  Note the first one never gets called back for body.  Does anyone else have this problem?

2016-06-17T18:38:18.443Z	a8c47f2a-34ba-11e6-8a53-336b681b6287	dispatch intent = ResumeIntent 
2016-06-17T18:38:18.443Z	a8c47f2a-34ba-11e6-8a53-336b681b6287	ResumeIntent received 
2016-06-17T18:38:18.444Z	a8c47f2a-34ba-11e6-8a53-336b681b6287	debug: undefined = shanesoffice 
2016-06-17T18:38:18.444Z	a8c47f2a-34ba-11e6-8a53-336b681b6287	Sending HTTPS request to: /shanesoffice/play 
2016-06-17T18:38:18.665Z	a8c47f2a-34ba-11e6-8a53-336b681b6287	Sending HTTPS request to: /shanesoffice/play 
2016-06-17T18:38:20.083Z	a8c47f2a-34ba-11e6-8a53-336b681b6287	debug: final body =  
2016-06-17T18:38:20.083Z	a8c47f2a-34ba-11e6-8a53-336b681b6287	debug: genericResponse(undefined, ... undefined) 
END RequestId: a8c47f2a-34ba-11e6-8a53-336b681b6287

**Comment by GregRocket** [comment]
If you are saying that every other request is not executing, then no I am not experiencing this.

**Comment by kshartman** [comment]
OK it must be something specific to me

**Comment by GregRocket** [comment]
@kshartman I would suggest, if you are not already doing so, start using the Beta Branch of node-sonos-http-api

**Comment by GregRocket** [comment]
@kshartman And one more thought is you might try increasing the lambda time out to say 30 seconds in the Lambda Management Console.
