### ISSUE TITLE
All sonos amps respond except one

### ISSUE THREAD

**Issue by themessings** [rgraciano/echo-sonos#4]
I 4 sonos amps.  3 of the 4 respond except the master bedroom.  I have checked the preset file and all looks to be OK.  Any ideas?

pi@raspberrypi ~ $ wget http://localhost:5005/master/play
--2015-08-11 03:08:41--  http://localhost:5005/master/play
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:5005... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37 [application/json]
Saving to: `play.20'

100%[======================================>] 37          --.-K/s   in 0s

2015-08-11 03:08:41 (836 KB/s) - `play.20' saved [37/37]

**Comment by rgraciano** [comment]
This is more a question for [node-sonos-http-api] (https://github.com/jishi/node-sonos-http-api), because we delegate Sonos control to that library.  Check case sensitivity and make sure the string name for that speaker looks *exactly* right.
