### ISSUE TITLE
Lambda newbie issue - creating service

### ISSUE THREAD

**Issue by tallbear** [rgraciano/echo-sonos#42]
I am having issue creating the AWS Lambda service

I have created the zip file with my edited options.js, index.js, AlexaSkills.js.  The zip files does not have a directory or anything else in it just the intended files.  When I create the function I get the following message:

It looks like your Lambda function "sonos" is unable to be edited inline, so you need to re-upload any changes.

**Comment by jhmartin** [comment]
Thats normal -- you don't get to see the sourcecode online.

**Comment by tallbear** [comment]
ok thanks...So the next step is Once created, click "Event Sources".

I see no event sources.  I see triggers and I could add a Alexa Skills trigger is this the correct thing?  The Doc is lacking a bit <grin>.  I get this:

Congratulations! Your Lambda function "sonos" has been successfully created.
Successfully added the trigger Alexa Skills Kit to function sonos. The function is now receiving events from the trigger. To configure the Alexa service to work with your Lambda function, go to the Alexa Developer portal.

Then when I configure the test I get:

{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "The Lambda service encountered an error: socket hang up"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}

**Comment by jhmartin** [comment]
Selecting Alexa Skills Kit is correct, thats point 9 under the lambda installation procedure.

The response tells me it tried to connect to the nodeJS app and failed.  Are you able to hit the nodeJS app remotely?

**Comment by tallbear** [comment]
thanks for your help!

Yes I can access it remotely without any issue example doing zones and see all the zones infor response.  The error I am getting error:

{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "The Lambda service encountered an error: connect ECONNREFUSED 68.106.247.177:5005"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}

**Comment by tallbear** [comment]
oh the ip and port are connect BTW...68.106.247.177:5005

**Comment by jhmartin** [comment]
When checking, are you checking from someplace within amazon? (Like a temporary t2.nano?)  

CONNREFUSED is a pretty affirmative response that Lambda was not able to get to your nodeJS app.

**Comment by tallbear** [comment]
nope from my phone via lte on the internet.

How can I test from t2.nano?

**Comment by jhmartin** [comment]
I mean, you can launch a very small (ie nano) sized instance in AWS, then do 'telnet 68.106.247.177 5005' and see if you get a connection or not.

**Comment by tallbear** [comment]
I was was able to figure out (way easy) to get a nano up and running and it can get to my node-sonos-http-api just fine (see below)

Last login: Sat Jul 16 23:15:52 2016 from ip68-106-247-177.ph.ph.cox.net

       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-ami/2016.03-release-notes/
3 package(s) needed for security, out of 12 available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-172-31-51-75 ~]$ wget tallbear.mooo.com:5005/zones
--2016-07-16 23:16:59--  http://tallbear.mooo.com:5005/zones
Resolving tallbear.mooo.com (tallbear.mooo.com)... 68.106.247.177
Connecting to tallbear.mooo.com (tallbear.mooo.com)|68.106.247.177|:5005... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14091 (14K) [application/json]
Saving to: ‘zones.2’

zones.2             100%[===================>]  13.76K  89.5KB/s    in 0.2s    

2016-07-16 23:16:59 (89.5 KB/s) - ‘zones.2’ saved [14091/14091]

**Comment by tallbear** [comment]
I got it sort of working thanks for all your help!

**Comment by jhmartin** [comment]
@tallbear can you post the root cause? (See https://xkcd.com/979/)
