### ISSUE TITLE
Lambda error

### ISSUE THREAD

**Issue by discokill** [rgraciano/echo-sonos#43]
Hi, apologies if this isn't the right place for this.  I'm a complete newbie at this but have managed to make it through the steps so far so good.  However at the Lambda test stage I get the following error thrown:

`{
  "errorMessage": "Cannot find module 'index'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._resolveFilename (module.js:338:15)",
    "Function.Module._load (module.js:280:25)",
    "Module.require (module.js:364:17)",
    "require (module.js:380:17)"
  ]
}`

Any idea what might be causing this?

**Comment by jhmartin** [comment]
I suspect you made a mistake when zipping. Did you zip up the js files, or did you zip up the directory *containing* the js files? It should be the former.

**Comment by discokill** [comment]
I believe I saved them to my desktop created a folder called "src" (or whatever the folder was called) and zipped it using mac's built in utility.  Thank you for the direction pointing, I'll try redoing the skill creation steps, hopefully that will help.

**Comment by discokill** [comment]
Closing the issue - re-created the files taking care to make sure files were only edited in plain text and followed zipping exactly as instructed on the readme and it seemed to work.  Thank you for the assistance
