### ISSUE TITLE
Lambda error

### ISSUE THREAD

**Issue by theroamingbone** [rgraciano/echo-sonos#45]
I'm getting the following error when I test:

Execution result:
{
  "errorMessage": "Unexpected token <",
  "errorType": "SyntaxError",
  "stackTrace": [
    "Module._compile (module.js:439:25)",
    "Object.Module._extensions..js (module.js:474:10)",
    "Module.load (module.js:356:32)",
    "Function.Module._load (module.js:312:12)",
    "Module.require (module.js:364:17)",
    "require (module.js:380:17)"
  ]
}

log output:
START RequestId: 1f792b59-5027-11e6-88ff-fdf244a4bc7d Version: $LATEST
Syntax error in module 'index': SyntaxError
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
END RequestId: 1f792b59-5027-11e6-88ff-fdf244a4bc7d
REPORT RequestId: 1f792b59-5027-11e6-88ff-fdf244a4bc7d  Duration: 0.38 ms   Billed Duration: 100 ms     Memory Size: 128 MB Max Memory Used: 15 MB

**Comment by theraptscallion** [comment]
I'm getting the same error.  I previously had it working, but after a move and a shifting of VPNs, I can no longer get the Lambda end of things to work.  Test produces the same error, but I'm sure my server is exposed. I've tried wiping everything and starting from a clean slate, but no love at all now.

**Comment by rgraciano** [comment]
@theraptscallion - any luck?  This error would indicate a syntax error somewhere
