### ISSUE TITLE
systemctl echo-sonos.service

### ISSUE THREAD

**Issue by bradanlane** [rgraciano/echo-sonos#47]
If there is any interest, I have created a systemctl file for `echo-sonos.service` for anyone who plans to run this as a server task. It works well on a Raspberry Pi 2 and makes a handle little Internet appliance.

**Comment by jratliff681** [comment]
I'd like to see your service file if you don't mind or just paste it here. I made one but it keeps failing, so I had to start mine through rc.local instead. I'm not sure why, I have several other programs starting as services, but none of them are node files so maybe I missed something.

**Comment by rgraciano** [comment]
@bradanlane, feel free to add a PR
