### ISSUE TITLE
Groups Broken

### ISSUE THREAD

**Issue by andyadler** [rgraciano/echo-sonos#49]
When I ask Alexa to play a preset the sonos groups are broken.  So if I have three rooms in the players entry of a preset and those three rooms are grouped, when I ask to play the preset the rooms are no longer grouped.

Is this by design?  

Is there a way to avoid this?

Andy Adler

**Comment by rgraciano** [comment]
Please give it a shot with the new version of echo-sonos and node-sonos-http-api, as this functionality has been fixed & improved
