### ISSUE TITLE
presets file has small bug, causes group presets to fail

### ISSUE THREAD

**Issue by jrluw** [rgraciano/echo-sonos#50]
If you edit the default presets.json file, and leave in the "uri" definitions, a long asynchronous series will fail in the middle.  sonos.js _does_ check for whether presets.uri is defined and, if so, attempts to actually set the URI accordingly.  Sonos barfs on this, and it messes up all the calls that come later.  Most importantly, the calls that are meant to define the coordinators of the other group members.  Just delete the URI definitions, and everything works flawlessly.

**Comment by jrluw** [comment]
Along these lines, the beta tree of sonos-discovery uses promises and is much easier to understand/debug.

**Comment by rgraciano** [comment]
Thanks - should no longer be an issue in current build.  Removed instruction from documentation
