### ISSUE TITLE
Build-in slot type AMAZON.LITERAL is forbidden

### ISSUE THREAD

**Issue by nickrace** [rgraciano/echo-sonos#55]
Great work! Just trying to set this up in the UK now that the Echo has been announced.  I've hit an initial problem trying to save the Interaction Model, which looks related to the fact that I'm using a different locale, although this will also become an issue within the US shortly.  When I attempt to save the Interaction Model I receive the following message:

Error: There was a problem with your request: The build-in slot type AMAZON.LITERAL is forbidden in current locale 

Digging a little further, I find:

English (US) skills using the AMAZON.LITERAL slot type should be updated to use custom slots. Starting November 30, 2016, any English (US) skill using AMAZON.LITERAL will no longer pass certification.

English (UK) and German skills do not support AMAZON.LITERAL and cannot use the AMAZON.LITERAL slot type.

Does anyone have an intent schema that works around this issue?

Thanks,

**Comment by danielhomer** [comment]
Try replacing all instances of AMAZON.LITERAL with LITERAL. I had the same issue the evening and it seems to work with this tweak.

**Comment by nickrace** [comment]
Cheers - that works!

**Comment by andyhud** [comment]
Hi Nick/Daniel

I'm in UK also and have the node-sonos-http-api working on my Raspberry PI. I can URL to http://IPofPI:5005/Zones and get all my Sonos back. I can even play a playlist etc.

I've setup a Lambda account and created my "src.zip" file but after I create the Lamdba function (with node.js 4.3) I dont ever get the "Event Sources" tab so I can't get any further. I've recreated on N.Virginia and Europe (Ireland) which both support the Alexa Skill Set but I can't for the life of me get Event Sources to appear

In my src.zip file I have options.js + AlexSkill.js  and Index.js

Any idea what I'm doing wrong to not get the Event Sources tab to show?

Thanks

Andy

**Comment by jratliff681** [comment]
There isn't an "Event Sources" tab, go to the "Triggers" tab and click add trigger.
Lots of little stuff has changed or moved on the aws and developer sites over the past year.

**Comment by andyhud** [comment]
Hi Jratliff681

Thanks, I'm a noob to all this and just trying to follow a guide and never even bothered to look there. I have found it, so thankyou

Andy

**Comment by jratliff681** [comment]
No problem, glad I could help!
