### ISSUE TITLE
The remote endpoint could not be called

### ISSUE THREAD

**Issue by GregRocket** [rgraciano/echo-sonos#56]
@jplourde5 This is odd behavior. If I ask sonos to play an album from the sonos library the album loads and plays.

Some albums get the lampda response "The remote endpoint could not be called, or the response it returned was invalid." Other albums get the correct lampda "Queued and started ALBUM NAME"

The same albums get the same response each time. I am not sure what could be the problem with the album names that get the error.

**Comment by jplourde5** [comment]
See if the problem names have special characters like ' , etc..  I've seen some problems with that.  Let me know.

**Comment by GregRocket** [comment]
@jplourde5 

Here are two mp3 tags exported using mp3tag software. Neither have any special characters.
Journey  -  Evolution  -  Majestic  -  1  -  1979  -  Rock  -  
Rod Stewart  -  Every Picture Tells a Story  -  Every Picture Tells a Story  -  1  -  1971  -  Rock  - 

"Journey" , "Evolution" will load and the lampda response is correct. "Queued and started evolution"

"Rod Stewart" , "Every Picture Tells a Story" will load and play but the lampda response is always "The remote endpoint could not be called, or the response it returned was invalid."

**Comment by GregRocket** [comment]
@jplourde5 
Trying to figure out what is going on, I renamed the Rod Stewart Album "Every Picture Tells a Story" to "Every Picture Tells". Re-indexed sonos library and ran load. Asked sonos to play album "Every Picture Tells" and the album loaded, played and the received correct lampda response "Queued and started every picture tells"

I then renamed the album back to "Every Picture Tells a Story", re-indexed everything and asked sonos to play the album. All worked except the lampda reponse is again "The remote endpoint could not be called, or the response it returned was invalid."

I've run across a few albums so far that get the lampda error. I really can't tell why this is happening, all the tags look good.

A couple of other examples, Black Sabbath's "Sabbath Bloody Sabbath" and Journey's "Look Into The Future", also give the lampda error response.

**Comment by jplourde5** [comment]
I worked on the album track order fix, which appear to be working but it wasn't a trivial change so I'm doing some more testing.  As part of the fix, I don't include the title in the metadata because I've seen other problems with it.  Until I push the fix, try this:

Edit the libraryDef.js file.  Look for getMetadata, remove the ${title} from the metadata string and see what happens.

**Comment by GregRocket** [comment]
Fixed with beta 2.4 Thanks so much for your efforts!
