### ISSUE TITLE
Error when testing

### ISSUE THREAD

**Issue by pokey800** [rgraciano/echo-sonos#58]
Hi,

I get the following when running the Lambda test. Can someone please offer some help.

{
  "errorMessage": "In strict mode code, functions can only be declared at top level or immediately within another function.",
  "errorType": "SyntaxError",
  "stackTrace": [
    "Module._compile (module.js:439:25)",
    "Object.Module._extensions..js (module.js:474:10)",
    "Module.load (module.js:356:32)",
    "Function.Module._load (module.js:312:12)",
    "Module.require (module.js:364:17)",
    "require (module.js:380:17)"
  ]
}

**Comment by castlesi** [comment]
I get the same issues.  Trying to set this up for the UK delivery of Dots tommorow.

**Comment by castlesi** [comment]
Just fixed this, try changing to node.js 4.3 despite what the instructions say.

**Comment by MatthewAlner** [comment]
@castlesi I'm Interested to know if you got this working in the UK? i'm having issues. Alexa won't recognise the sonos skill iv made. I'm thinking it might be because its a US skill and I need to make the UK language variant however the AMAZON.LITERAL slot type is not supported by the English (UK) and German (Deutsch) Alexa languages. They also plan to deprecate this slot type in English (US).

**Comment by thosirl** [comment]
See #55  "Try replacing all instances of AMAZON.LITERAL with LITERAL. I had the same issue the evening and it seems to work with this tweak."

**Comment by castlesi** [comment]
I tried to add the UK language to my existing skill that had the US language but it refused to let me add the custom slot types without filling in the intent schema which I cant do without the custom slot types.

**Comment by MatthewAlner** [comment]
Thanks @thosirl that worked perfectly :)

@castlesi I had the same issue, just put anything to satisfy the linter I used the example from [here](https://developer.amazon.com/edw/home.html#/skill/amzn1.ask.skill.60a5aed4-3559-4679-a36d-28449cc16692/en_GB/intentSchema/list) then replace it once you have added the slots

**Comment by webvictim** [comment]
The link in @MatthewAlner's last comment doesn't work, but I made up some random stuff to satisfy the linter and thought I'd add it here. 

Intent Schema:

`{
  "intents": [
    {
      "intent": "TellMeAJokeIntent"
    }
  ]
}`

Sample Utterances:

`TellMeAJokeIntent tell me a joke`

**Comment by thosirl** [comment]
I had similar problem, but the trick was to put in a reduced intent schema  without calling any custom slots, then add the custom slots, and then go back and add the full intent schema.
