### ISSUE TITLE
echo-sqs-proxy access denied

### ISSUE THREAD

**Issue by GregRocket** [rgraciano/echo-sonos#59]
I setup the latest version of **echo-sonos**, created a directory "echo-sqs-proxy" on the same server running node-sonos-http-api and ran **npm install --production**.  Retrieved new credentials and edited settings.json. Ran **npm start** with no errors. In options.js file I set useSQS to true.  AmazonSQSFullAccess policy was already set up and working. Zipped up files to Lambda and saved.

When I ask sonos to run a command I see **Access Denied** error in the echo-sqs-proxy api directory.

**Comment by rgraciano** [comment]
@GregRocket - any luck getting it to work since?

**Comment by GregRocket** [comment]
@rgraciano No luck, I could not get this to work.

**Comment by GregRocket** [comment]
I revisited this and I have it working. Still get a console error message "access denied" but it is working.

**Comment by GregRocket** [comment]
Hmm.. Thought I had it working but it's not.

**Comment by Zmav** [comment]
I too have run into this issue, i think its a problem with authentication. i only see it when i try to enable authentication on the Sonos API node,it seems echo can communicate with the SQS-proxy fine, but when it passes the command to the Sonos API it doesnt seem to authenticate. I've tried everything my limited java skills can think off but this my first attempt playing with it.

**Comment by GregRocket** [comment]
@Zmav That seems to be the problem "the command to the Sonos API it doesnt seem to authenticate" I've tried to get this to work but just can not.

**Comment by Zmav** [comment]
I've got so far as adding the dependency for Basic-auth to Sonos SQS, and the login information, but i'm unsure how to add the code that makes it use that information yet, i think i can cut and paste and edit the code for the basic auth from either server.js from the API or the Lambda function both contain code about basic auth. But as i only started learning java to get this working 2 days ago, its gonna take me some time. I think we need someone with a lot better skill with java. But i'm also working on getting the Amazon Audio commands to integrate with the skill as well. So ill get there just have to learn java first.

**Comment by GregRocket** [comment]
@rgraciano I've isolated the problem. If I remove username and password from the settings.json for the node.api then sqs works. 

Is username and password not needed for security with sqs proxy or does passing the username and password need to be added to sqs?

Thanks!

**Comment by GregRocket** [comment]
I got it all sorted out. Thanks!

**Comment by j0aker** [comment]
Hi, don't mean to drudge up old threads, but how was this sorted out?  I'm having the same issue as GregRocket and am also seeing that removing the username and password from settings.json for node-sonos-http-api allows the SQS proxy to work.  Can they not be used together?

Thanks,
-J

**Comment by GregRocket** [comment]
@j0aker That was some time I ago. I currently use PM2 to run both the SQS proxy and Sonos API. Just be sure to cd into the directory you have the SQS proxy files and start the SQS proxy. Then cd to the Sonos API dirctory and start that program.
