### ISSUE TITLE
Alexa discovery not working

### ISSUE THREAD

**Issue by castlesi** [rgraciano/echo-sonos#60]
I am in the UK and have the lambda function testing correctly in EU West using the echo-sqs-proxy and I can test the Alexa skill successfully as well, with UK Language per previous issue.

{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "PlainText",
      "text": "OK"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}

I can view the zones with IPofPi:5005/zones so that bit works too.

However Alexa cannot discover my devices.

**Comment by MarkDiddams** [comment]
What issue exactly do you have? Does it work if you try to play a song directly putting into the URL? But when you say Alexa play rock it then says ok and does nothing?

**Comment by castlesi** [comment]
Haha.. I think I was getting confused with how my Vera skill that I just activated and this work.  The Vera skill is a smarthome skill and exposes all my devices to Alexa so she can discover them and control them natively. 
I now realise that this is a standalone skill that I activate by using its keyword, and should not be expecting to see the Sonos speakers "discovered".  is this correct?
Hopefully this means I have this working, I just need to try talking to Alexa.

**Comment by MarkDiddams** [comment]
Hi,

I don't have Alexa showing my devices either, I don't think that's the purpose of the application. Instead under "my skills" it shows "sonos" as this is what I called it on the AWS service and the Alexis Skill site. I can then say "Echo (as i've changed the name, Play Rock in the bedroom)" and it will que my Rock playlist in the Sonos app. I have yet to work out how to get it to play songs from spotify. at the moment I have to actually add the spotify songs to my sonos Rock playlist. 

Is there any other errors you are getting that I can perhaps try and help with?
