### ISSUE TITLE
issue with intent schema, fairly new at this

### ISSUE THREAD

**Issue by validoption** [rgraciano/echo-sonos#61]
First, everything has been working swimmingly through the initial node setup and the readiness for the outside world (ddns).  I'm at the Alexa Skill creation part, and this is where I'm hanging up. 

I've created the custom slots and copied in the appropriate info from the files.  I've copy/pasted the intent schema and the utterances.  However, when I go to save it, I get this error: 

Error: There was a problem with your request: Error in sample on line 21 - 'MusicIntent play {coldplay|name} in the {Room}'. The given intent doesn't declare the slot 'name'.

Not really sure how to address this, and didn't (couldn't) find anything in searches related to this, so any guidance is super appreciated. 

Thanks!

**Comment by gijoecool** [comment]
I believe 'Name' should be capitalized.

**Comment by validoption** [comment]
Thank you; in the intent file --

 {
      "intent": "MusicIntent",
      "slots": [
        {
            "name": "Name",
            "type": "AMAZON.LITERAL"

or in the utterance file? 
MusicIntent play {coldplay|name} in the {Room}

**Comment by gijoecool** [comment]
They must match. If it's capitalized in one, then it should be capitalized in the other.

The error on the other hand seems to contradict Amazon documentation: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interaction-model-reference#literal-slot-type-reference

It says there that examples must be given for slots of type AMAZON.LITERAL. However, your error seems in conflict with that requirement.

Could you try changing AMAZON.LITERAL to just LITERAL? The documentation says that AMAZON.LITERAL is no longer supported at the end of the month. I know folks in UK and Germany had issues with AMAZON.LITERAL not working.

**Comment by validoption** [comment]
After making that change to the five or so instances in the intent schema (and leaving AMAZON.NUMBER alone), it Successfully updated the interaction model.

THANK YOU!

**Comment by arpita8** [comment]
I am getting an error " Error: There was a problem with your request: Invalid intent name 'null'.
", what can be the problem?

**Comment by ghost** [comment]
If anyone else has this issue, I found that the beta Interaction model isn't the most obvious thing in the world. You not only have to 'save' it, but also 'build' it too. Once you build it, you can then enable testing.
