### ISSUE TITLE
utterances error

### ISSUE THREAD

**Issue by farberm** [rgraciano/echo-sonos#63]
I received the following error when I copy and paste the utterances in to the sample utterances

Error: There was a problem with your request: Incorrect syntax: A value may not be supplied for the slot 'Name'. Occurred in sample 'MusicIntent play {coldplay|Name} in the {Room}' on line 21. 

This happpens for several of the lines in the code?

Is there a newer file to copy utterances from?

**Comment by gijoecool** [comment]
Take a look at #61.

**Comment by farberm** [comment]
Thanks fixed the issue
