### ISSUE TITLE
Alexa Skill error - "The remote endpoint could not be called..."

### ISSUE THREAD

**Issue by farberm** [rgraciano/echo-sonos#68]
I have Lambda now woiking with the test code. 

I cannot get any code to test thru the skills panel however. 

I get the following error when I use the same code via the Skill setup in Alexa Skills control panel. I have chosen custom skill, invocation - sonos, Global fields - no, followed instructions for slot yype and  schema. Chose endpoint configuration as AWS Lambda ARN (not HTTP?), North America and no account linking.

When I test the same code that worked in Lambda  set up I get the following error

"The remote endpoint could not be called, or the response it returned was invalid."

Lastly - Publication Information is not highlighting Green check even though everything is filled out

**Comment by gijoecool** [comment]
I'm just shooting in the dark here... do you have your skill pointing back to the correct address and port, and the correct ports open in your router/firewall? Or are you using SQS?

**Comment by farberm** [comment]
I have port 5005 open and pointing to my server. I checked that I can connect to it thru 
my_ip_address:5005/zones and I get a response.

I did not see any instruction n how to point the skill back to the server adress. Where do I find that info on how to make that happen.

**Comment by gijoecool** [comment]
Can you access this from an outside computer or mobile phone not on your wifi network? For example, turn off wifi on your mobile phone, and then go to http://my_ip_address:5005/zones. If you cannot connect to this from outside your network, then this is the same problem that your skill is having.

**Comment by farberm** [comment]
Just reverified that with my wifi off on my cell I can connect to http://my_ip_address:5005/zones
and I get an entire page of response abut the sonos players on the netwoek

**Comment by farberm** [comment]
Fixed. Had to set timeout to 30 sec and reinput the ARN name from Lambda. Now working just slow to espond
