### ISSUE TITLE
PRESETS Not working as expected

### ISSUE THREAD

**Issue by GregRocket** [rgraciano/echo-sonos#74]
Lastest buids of API and Echo-Sonos

I've setup a number of presets. Instead of using the default names for presets, I want to use my own names.

My understanding is that Preset is the default behavior.

Now if I issue the command "ask sonos to play PRESET" some work and others don't.
They all work if I issue the command "ask sonos to play preset PRESET" but that gets to be a mouthful. I'd rather not to have to say preset, just the preset name.

Here is a sample of some of my PRESETs (bold presets work without saying the word preset):

front yard 70s rock
front yard 80s pop
**front yard classic rock**
front yard eagles

**backyard 70s rock**
**backyard 80s pop**
**backyard beatles**
**backyard classic rock**
**backyard eagles**

master 70s rock
master 80s pop
master classic hits
**master eagles**

70s rock
80s pop
**classic rock**
**eagles**

**Comment by GregRocket** [comment]
@jplourde5 If **PRESET** is the music service, then shouldn't I be able to issue the command "ask sonos to play PRESET" without having to add the word "preset" to the command? Please read my first post to see my problem. Thanks!

**Comment by jplourde5** [comment]
Do you have advanced mode turned on in your settings?  If not, then the solution should follow the old behavior where everything is considered a preset.  In that case, you want to make sure that your PRESETS slot contains all of your desired values or the Alexa service translation will lose accuracy.

If Advanced Mode is turned on then there are two ways to invoke PRESETS, one by saying "play preset...", and another by changing your current music service to "presets" and then simply saying "play PRESET".

**Comment by GregRocket** [comment]
@jplourde5  Yes I have advanced mode turned on. I do have PRESETS slots of all my desired values.

I've set preset as the default behavior in settings. I verify I am in preset mode by issuing command "Alexa, ask sonos to change music to presets"

For example if I use the Developer Console Test page and type in the command I can see the Lambda Request.

If I try "ask sonos to play master classic hits"
Lambda request show the word master is dropped.

"intent": {
      "name": "PlayPresetIntent",
      "slots": {
        "Preset": {
          "name": "Preset",
          "value": "classic hits"
        },
        "Room": {
          "name": "Room"

If I try "ask sonos to play master eagles" the lambda request shows:
    "intent": {
      "name": "MusicIntent",
      "slots": {
        "Room": {
          "name": "Room"
        },
        "Name": {
          "name": "Name",
          "value": "master eagles"

**Comment by jplourde5** [comment]
What is the actual name of your room?  It seems to be "Room".  If that is not right, try saying "Ask Sonos to change room to XXXX.

If that doesn't fix it, look at the values in DynamoDB and see what it has for service and room.

**Comment by GregRocket** [comment]
@jplourde5 When you say actual name of room, what do you mean? I am just trying to call a PRESET that groups some rooms together. In the above examples the rooms are master bedroom and maser bathroom.

I notice the first try the intent is "name": "PlayPresetIntent",
The next try the intent name is "name": "MusicIntent",

**Comment by jplourde5** [comment]
Try "Alexa, Ask Sonos to change room to Master Bedroom"

And then try again.

In Advanced Mode, Presets is not the default and you would normally need to say "Alexa, Ask Sonos to play preset xxx".  However, if Presets is your current music service, it should work without having to say "presets".  The one odd thing that I see with:

"intent": {
"name": "MusicIntent",
"slots": {
"Room": {
"name": "Room"
},
"Name": {
"name": "Name",
"value": "master eagles"

Is that the room name is set to "Room".  "Room" should be showing as Master Bedroom, Master Bath, etc., and I'm wondering if you have a blank value stored in the defaults used by Advanced mode. I understand that Presets specify their own rooms, but I'm just wondering if the "Room" value is breaking something.

**Comment by GregRocket** [comment]
@jplourde5 Setting room to master bedroom had no effect. I don't see a blank value.

Here is my room slots:
backyard
front yard
garage
hall bathroom
ladies room
master bathroom
master bedroom
media room
office

I tried removing all the rooms except backyard.
Tried "ask sonos to play master seventies rock" with same results.
    "intent": {
      "name": "PlayPresetIntent",
      "slots": {
        "Preset": {
          "name": "Preset",
          "value": "70s rock"
        },
        "Room": {
          "name": "Room"

**Comment by GregRocket** [comment]
@jplourde5 I took a look at what happens when I try and set room to ROOM. Something looks wrong to me here.

"ask sonos to change room to master bedroom"
    "intent": {
      "name": "ChangeRoomIntent",
      "slots": {
        "Room": {
          "name": "Room"
        }

If I try "ask sonos to change service to library" I get the result I would expect.
    "intent": {
      "name": "ChangeServiceIntent",
      "slots": {
        "Service": {
          "name": "Service",
          "value": "library"
        }

**Comment by GregRocket** [comment]
@jplourde5 I turned off advanced mode in options.js and uploaded files.

I tried "ask sonos to play master seventies rock"
Same results as before:
    "intent": {
      "name": "PlayPresetIntent",
      "slots": {
        "Preset": {
          "name": "Preset",
          "value": "70s rock"
        },
        "Room": {
          "name": "Room"
        }

**Comment by GregRocket** [comment]
@jplourde5 
If I add preset then it works. "ask sonos to play **preset** master seventies rock"

    "intent": {
      "name": "PlayPresetIntent",
      "slots": {
        "Preset": {
          "name": "Preset",
          "value": "master 70s rock"
        },
        "Room": {
          "name": "Room"
        }

**Comment by jplourde5** [comment]
The PlayPresetIntent should have already been there.

{
      "intent": "PlayPresetIntent",
      "slots": [
        {
            "name": "Preset",
            "type": "PRESETS"
        },
        {
            "name": "Room",
            "type": "ROOMS"
        }   
      ]
    },
  
And you should have a PRESETS slot definition that includes "master 70s rock" as well as any other preset names that you have, and the preset names will need to match the spelling of your actual presets.

Here is what happens.

1) You utter something to the Echo and it sends it to the Alexa cloud solution

2) It tries to match what you uttered to something in your PRESETS slot values or makes a best guess at what you said if it can't find something that looks close

3) It passes what it arrives at for the the preset value to your Lambda function

4) The Lambda function passes the preset value to the node-sones-http-api solution spelled exactly as it was passed from the Alexa function

5) The spelling has to match exactly the spelling of your preset in the n-s-h-a or the preset will not play

What could easily be happen is that the Alexa solution is not getting your spelling right.  Check your history in the Alexa app on your mobile device and see what it is arriving at for the spelling.

**Comment by GregRocket** [comment]
First thanks for your help. This is a complicated problem and I am trying to give you detailed information on the problem. 

I do have slot definitions setup for each and every preset name. Each preset slot name matches the spelling of an actual presets.json.

Slot Name = Preset.json name
Slot name, "master 70s rock" has a json file name "master 70s rock.json" as are all other presets setup.

For testing purpose I am using the Amazon Developer Console > Test > Service Simulator. Using the Service Simulator I can see exactly what the "Lambda Request" sent to the api is.

I am copying and pasting the Preset Name to the Amazon Developer Console Test's "Enter Utterance" field to ensure that utterance is spelled correctly and matches the Slot Name and json file name.

For a test I enter the commands in the Amazon Developer Console Service Simulator.
There is a Slot Name "master 70s rock" in Custom Slot Types PRESETS. There is a also a "master 70s rock.json" file.

Enter Utterance:
ask sonos to play master seventies rock

The Lambda Request response:
    "intent": {
      "name": "PlayPresetIntent",
      "slots": {
        "Preset": {
          "name": "Preset",
          "value": "70s rock"
        },
        "Room": {
          "name": "Room"
        }

There can be no mistake that "play master seventies rock" was asked, as it is typed in, not spoken. The Lambda Request, for whatever reason, drops master and passes on the value "70s rock" instead of "master 70s rock"

It makes no difference if I use the simulator or speaking into Amazon Echo device. The results are the same. Some work, others don't. The ones that work, always work and the ones that don't, always don't.

My first post has examples of what works and what does not. Each of the presets had a slot entry and a json file named the same.

Again if I just add the word preset to the command then they all work. But if I have PRESETS set as default then I should not have to say play preset PRESET.

I don't think it's just a spelling error but something seems to be wrong in the Interaction Model.

Thanks for your help.

**Comment by GregRocket** [comment]
I just tried another test. I removed all the slot names except those that start with master. When there is only these entries then all master presets work. 

All worked.
master 70s rock
master 80s pop
master classic hits
master eagles

I'm going to add some more back a group at at time and see what happens.

**Comment by GregRocket** [comment]
So here is what I've discovered. 

**These presets all worked**
front yard 70s rock
front yard 80s pop
front yard classic rock
front yard eagles
backyard 70s rock
backyard 80s pop
backyard beatles
backyard classic rock
backyard eagles
master 70s rock
master 80s pop
master classic hits
master eagles

**As long as I don't add these presets in**
70s rock
80s pop
classic rock
eagles

**Comment by jplourde5** [comment]
Your problem is in the Alexa interpreter and l'm afraid that you are going to have to work around the problem by choosing a set of names that all work. I suspect that it could be getting confused by some of the similarities in the names.

**Comment by GregRocket** [comment]
Yea I'm think your right. Either I just add preset to the command or mess around with names that are going to work.

**Comment by GregRocket** [comment]
I have found a solution that works for me so far. I only use presets and the library services. I am using Amazon Prime for steaming music so can't use the API search features like available if I had Spotify.

My solution was to add "**PlayPresetIntent play {Preset}**" to the Alexa Skills Interactive model Sample Utterances. Now presets work the way I wanted. I ran a few test and all else seems to be working correctly. I am not sure if this change would effect Streaming Music Search or not as I can't test that, but Library still worked correctly searching for artist or album.

If I run into something that this change effects I'll post back here.

**Comment by rgraciano** [comment]
@GregRocket, thanks for closing the loop.  @jplourde5 - does this change break anything for you?  My rpi is packed away in a box somewhere while I do some remodeling work, so I can't test this.

**Comment by GregRocket** [comment]
@rgraciano Preset have been working perfectly now. I can also just drop a new preset.json file into the preset directory and the preset becomes instantly available. No need to add the preset to the Custom Slot Types PRESETS in developer console.

**Comment by rgraciano** [comment]
@GregRocket, I was actually concerned about the other stuff - whether or not this might break some of the advanced mode features.  The Alexa interpreter seems to work in mysterious ways

**Comment by GregRocket** [comment]
@rgraciano Yes, my concern also. But presets work so good now, the way they should. Library function works properly as does pause, resume, volume etc. The only thing I can not test is a streaming radio service such as spotify search function.

**Comment by jplourde5** [comment]
It shouldn't break anything.  I thought that the PlayPresetIntent was already there.  It was when I last checked.  Were any other changes made?

**Comment by GregRocket** [comment]
@jplourde5 

Line 135 **PlayPresetIntent play preset {Preset}** was there I added **PlayPresetIntent play {Preset}** just below this line. No other changes were made.

**Comment by jplourde5** [comment]
I think that will break everything else and why I included an advanced mode. The play intent will use presets if advanced mode is turned off.

**Comment by GregRocket** [comment]
@jplourde5 By everything else do you mean streaming radio services like Spotify? I only use the library search and presets modes and they work fine. Also I use Amazon music but that as you know has no search feature.

**Comment by jplourde5** [comment]
In my earlier testing the Alexa code would get confused about whether it was the play preset or play music service intent that was being called because they both start the same way, "Play xxx"
