### ISSUE TITLE
Advanced Mode not working

### ISSUE THREAD

**Issue by eyoung71** [rgraciano/echo-sonos#78]
I have attached the two policies and changed the advanced mode to true in options.js.
When I upload the new file it tests out fine on both Lamba and AWS. 
The test command works but other commands fail with 'the response is invalid' from lambda.
If I change advanced mode back to false then all commands work as expected.

**Comment by eyoung71** [comment]
I should also add that I get this when I start the server:

2016-11-17T01:39:03.815Z INFO no settings file found, will only use default settings

**Comment by rgraciano** [comment]
@eyoung71, the INFO message isn't anything to worry about.  Have you gotten it to work since posting?  Are you using the latest version of node-sonos-http-api?

**Comment by eyoung71** [comment]
I have not. If I change it to TRUE then it does not work.

**Comment by npwalker** [comment]
I'm also having this issue.  If I change advanced mode from false to true the lambda page shows the test as working but testing the skill from the webpage shows an invalid response from lambda.  

I have the same issue trying to change the defaultMusicService from presets to library.

**Comment by RogerFord** [comment]
Any update on this issue?  I've got things working nicely but when I switch to advancedMode:true Alexa replies with "There was a problem with the requested skills response" to anything I ask Sonos.

The comments in options.example.js say "Requires additional AWS setup" for advancedMode, but I can't find out what, if any, additional setup is required - or whether that's an old comment which is no longer relevant.

**Comment by RogerFord** [comment]
OK, figured it out. I needed to go to the IAM console https://console.aws.amazon.com/iam where it allows me to to create a new role with lambda_basic_excution and AmazonDynamoDBFullAccess. I was then able to specify this role for my Lambda function. Hope this helps someone.

**Comment by cdemots** [comment]
Thanks for the solution RogerFord. Instead of creating a new role, I was able to edit my existing role, and it works me now too.
Steps to add policy to role in IAM:
1. Click on the role here: https://console.aws.amazon.com/iam/home#/roles
2. On the Permissions tab, click Attach Policy
3. In the Policy Type filter box, type AmazonDynamoDBFullAccess
4. Select the policy when it shows up, and click Add Policy
