### ISSUE TITLE
UK use of LITERAL/AMAZON.Literal + Custom Slot Types

### ISSUE THREAD

**Issue by helenxxxx** [rgraciano/echo-sonos#81]
Hi guys,

We have been trying to get this working in the UK, and are getting as far as the test harness succeeding, but are unable to see Alexa control the Echo(we just get a message to try again later).  I think the issue may relate to the AMAZON.LITERAL support.  We have changed all instances to 'Literal' rather than the former, and this is accepted by the Skill but doesn't work.  

We have then tried to get custom slot types working, but despite double and triple checking the case of the Intent schema vs the Sample Utterances and Slot Type, we get this error:

**Error: There was a problem with your request: Incorrect syntax: A value may not be supplied for the slot 'Name'. Occurred in sample 'MusicIntent play {coldplay|Name} in the {Room}' on line 21.**

...this is the change we made(we have changed all instances in the Intent, but this is just an example):

{
    "intents": [
    
    {
      "intent": "MusicIntent",
      "slots": [
        {
            "name": "Name",
            "type": "NewLiteral"
        },
        {

![image](https://cloud.githubusercontent.com/assets/24213521/20652644/ce42d4ba-b4f4-11e6-8651-9f97f5a13182.png)

MusicIntent play {coldplay|Name} in the {Room}

I appreciate that this is an amendment to the core build, but I would be very thankful for any help :(

Thanks,
Helen

**Comment by chrisjholly** [comment]
This issue is very similar to https://github.com/rgraciano/echo-sonos/issues/70#issuecomment-264112175 which I am working on. Keep an eye on that issue.  I am from the UK too. 

I believe the utterance in your example should just be 'MusicIntent play {Name} in the {Room}' and "Coldplay" should be a value in your custom slot called NewLiteral.

**Comment by ecairncross** [comment]
Also having this issue. Any help would be appreciated...

**Comment by chrisjholly** [comment]
@smulube has submitted a pull request with a fix - https://github.com/rgraciano/echo-sonos/pull/85 - try it out!

**Comment by rgraciano** [comment]
Fixed in #85
