### ISSUE TITLE
is "line in" a possibility?

### ISSUE THREAD

**Issue by At0mM0nk3y** [rgraciano/echo-sonos#94]

**Comment by pheintzelman** [comment]
I am working on adding this. I have my dot connected to a linein which is great. I recommend this setup. I am adding linein with this setup in mind.

//Adding
options.defualtLineIn = '[DotLineIn]'

PlayInRoomIntent play in {Room}        
PlayInRoomIntent play in the {Room}
...

LininIntent to set {Room} line-in in to {LineIn}
LininIntent set {Room} line-in in to {LineIn}
LininIntent to use {LineIn} line-in in {Room}
LininIntent use {LineIn} line-in in {Room}
LininIntent have {Room} use {LineIn} line-in
...

Please suggest other utterances.

**Comment by rgraciano** [comment]
@At0mM0nk3y - this is in now, thanks to @pheintzelman
