### ISSUE TITLE
Input test on Lambda producing ENOTFOUND

### ISSUE THREAD

**Issue by sgusberg** [rgraciano/echo-sonos#98]
My test of the function on Lambda is producing "The Lambda service encountered an error: getaddrinfo ENOTFOUND" and then "mydyndnsaddress mydyndnsaddress:5005". Testing mydyndnsaddress:5005 remotely seems to be working fine though.

Anyone have any ideas of what it might be??
Thx!

**Comment by steve772** [comment]
@sgusberg What did you do to fix this issue?  I am having the same exact error.

**Comment by sgusberg** [comment]
Hi Steve, I switched to a paid dynamic DNS service (dyn.com) which did the
trick. I'm not completely sure why, but when I was using a free service it
didn't work.
Good luck!
